// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: append.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertEvent = `-- name: InsertEvent :one

INSERT INTO events (
    event_id,
    tenant_id,
    stream_id,
    version,
    type_url,
    schema_version,
    occurred_at,
    correlation_id,
    causation_id,
    command_id,
    actor,
    actor_principal,
    payload,
    payload_json,
    encryption_key_refs
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING global_position, recorded_
`

type InsertEventParams struct {
	EventID           uuid.UUID
	TenantID          string
	StreamID          string
	Version           int64
	TypeUrl           string
	SchemaVersion     int64
	OccurredAt        string
	CorrelationID     uuid.UUID
	CausationID       uuid.UUID
	CommandID         uuid.UUID
	Actor             string
	ActorPrincipal    string
	Payload           []byte
	PayloadJson       *string
	EncryptionKeyRefs *string
}

type InsertEventRow struct {
	GlobalPosition int64
	RecordedAt     string
}

// Append-path queries for SQLite. Mirror of the Postgres adapter's
// append.sql, with two dialect deltas:
//
//   - No AdvisoryLock — SQLite serializes writers at the file level.
//     The "no-op" advisory lock exists in the adapter code as a stub
//     to keep the Append flow uniform across adapters.
//
//   - global_position comes from INTEGER PRIMARY KEY AUTOINCREMENT,
//     not nextval(). The INSERT omits the column; SQLite assigns it
//     and we read it back via RETURNING.
//
// Parameter syntax: bare `?` positional. sqlc 1.30's SQLite engine
// does not reliably handle `@name` or `sqlc.arg(name)` syntax in our
// setup, but positional `?` works and sqlc infers parameter struct
// field names from the column context.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.EventID,
		arg.TenantID,
		arg.StreamID,
		arg.Version,
		arg.TypeUrl,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.CorrelationID,
		arg.CausationID,
		arg.CommandID,
		arg.Actor,
		arg.ActorPrincipal,
		arg.Payload,
		arg.PayloadJson,
		arg.EncryptionKeyRefs,
	)
	var i InsertEventRow
	err := row.Scan(&i.GlobalPosition, &i.RecordedAt)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
t;

INSERT INTO outbox (tenant_id, global_position, event_id)
VALUES (?, ?,
`

type InsertOutboxParams struct {
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.ExecContext(ctx, insertOutbox, arg.TenantID, arg.GlobalPosition, arg.EventID)
	return err
}
