// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: append.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertEvent = `-- name: InsertEvent :execlastid

INSERT INTO events (
    event_id,
    tenant_id,
    stream_id,
    version,
    type_url,
    schema_version,
    occurred_at,
    recorded_at,
    correlation_id,
    causation_id,
    command_id,
    actor,
    actor_principal,
    payload,
    payload_json,
    encryption_key_refs
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	EventID           uuid.UUID
	TenantID          string
	StreamID          string
	Version           int64
	TypeUrl           string
	SchemaVersion     int64
	OccurredAt        string
	RecordedAt        string
	CorrelationID     uuid.UUID
	CausationID       uuid.UUID
	CommandID         uuid.UUID
	Actor             string
	ActorPrincipal    string
	Payload           []byte
	PayloadJson       *string
	EncryptionKeyRefs *string
}

// Append-path queries for SQLite. Mirror of the Postgres adapter's
// append.sql, with three dialect deltas:
//
//   - No AdvisoryLock. SQLite serializes writers at the file level;
//     the Append flow in the adapter code skips the AdvisoryLock step.
//
//   - global_position is INTEGER PRIMARY KEY AUTOINCREMENT, fetched
//     via database/sql's Result.LastInsertId() (`:execlastid`) rather
//     than RETURNING. This avoids a sqlc 1.30 SQLite tokenizer bug
//     that truncates trailing identifiers in RETURNING clauses.
//
//   - recorded_at is passed explicitly by the adapter (set to the
//     adapter-side clock at append time). The schema's DEFAULT remains
//     as a safety net for queries that omit it.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertEvent,
		arg.EventID,
		arg.TenantID,
		arg.StreamID,
		arg.Version,
		arg.TypeUrl,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.RecordedAt,
		arg.CorrelationID,
		arg.CausationID,
		arg.CommandID,
		arg.Actor,
		arg.ActorPrincipal,
		arg.Payload,
		arg.PayloadJson,
		arg.EncryptionKeyRefs,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (tenant_id, global_position, event_id)
VALUES (?, ?, ?)
`

type InsertOutboxParams struct {
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.ExecContext(ctx, insertOutbox, arg.TenantID, arg.GlobalPosition, arg.EventID)
	return err
}
