// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: append.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const backfillEventHash = `-- name: BackfillEventHash :execrows
UPDATE events
SET hash = ?, prev_hash = ?
WHERE tenant_id = ? AND event_id = ? AND hash IS NULL
`

type BackfillEventHashParams struct {
	Hash     []byte
	PrevHash []byte
	TenantID string
	EventID  uuid.UUID
}

// Populate hash + prev_hash for an event whose chain columns are NULL,
// as written by streams that existed before ADR 0028's tamper-evident
// chain migration. The `hash IS NULL` predicate is a safety guard: if
// the row already carries a hash, the UPDATE is a no-op (RowsAffected
// = 0) and the Go wrapper errors out, since overwriting an existing
// hash would silently mask tampering.
func (q *Queries) BackfillEventHash(ctx context.Context, arg BackfillEventHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, backfillEventHash,
		arg.Hash,
		arg.PrevHash,
		arg.TenantID,
		arg.EventID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertEvent = `-- name: InsertEvent :execlastid

INSERT INTO events (
    event_id,
    tenant_id,
    stream_id,
    version,
    type_url,
    schema_version,
    occurred_at,
    recorded_at,
    correlation_id,
    causation_id,
    command_id,
    actor,
    actor_principal,
    payload,
    payload_json,
    encryption_key_refs,
    hash,
    prev_hash
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	EventID           uuid.UUID
	TenantID          string
	StreamID          string
	Version           int64
	TypeUrl           string
	SchemaVersion     int64
	OccurredAt        string
	RecordedAt        string
	CorrelationID     uuid.UUID
	CausationID       uuid.UUID
	CommandID         uuid.UUID
	Actor             string
	ActorPrincipal    string
	Payload           []byte
	PayloadJson       *string
	EncryptionKeyRefs *string
	Hash              []byte
	PrevHash          []byte
}

// Append-path queries for SQLite. Mirror of the Postgres adapter's
// append.sql, with three dialect deltas:
//
//   - No AdvisoryLock. SQLite serializes writers at the file level;
//     the Append flow in the adapter code skips the AdvisoryLock step.
//
//   - global_position is INTEGER PRIMARY KEY AUTOINCREMENT, fetched
//     via database/sql's Result.LastInsertId() (`:execlastid`) rather
//     than RETURNING. This avoids a sqlc 1.30 SQLite tokenizer bug
//     that truncates trailing identifiers in RETURNING clauses.
//
//   - recorded_at is passed explicitly by the adapter (set to the
//     adapter-side clock at append time). The schema's DEFAULT remains
//     as a safety net for queries that omit it.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertEvent,
		arg.EventID,
		arg.TenantID,
		arg.StreamID,
		arg.Version,
		arg.TypeUrl,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.RecordedAt,
		arg.CorrelationID,
		arg.CausationID,
		arg.CommandID,
		arg.Actor,
		arg.ActorPrincipal,
		arg.Payload,
		arg.PayloadJson,
		arg.EncryptionKeyRefs,
		arg.Hash,
		arg.PrevHash,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (tenant_id, global_position, event_id)
VALUES (?, ?, ?)
`

type InsertOutboxParams struct {
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.ExecContext(ctx, insertOutbox, arg.TenantID, arg.GlobalPosition, arg.EventID)
	return err
}

const lastStreamHash = `-- name: LastStreamHash :one
SELECT hash FROM events
WHERE tenant_id = ? AND stream_id = ?
ORDER BY version DESC
LIMIT 1
`

type LastStreamHashParams struct {
	TenantID string
	StreamID string
}

// Returns the hash of the most recent event in a stream, used to
// chain the next append. Empty result for streams with no events.
func (q *Queries) LastStreamHash(ctx context.Context, arg LastStreamHashParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, lastStreamHash, arg.TenantID, arg.StreamID)
	var hash []byte
	err := row.Scan(&hash)
	return hash, err
}
