// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: constraint.sql

package db

import (
	"context"
)

const claimUnique = `-- name: ClaimUnique :exec

INSERT INTO unique_claims (tenant_id, scope, value, stream_id)
VALUES (?, ?, ?, ?)
`

type ClaimUniqueParams struct {
	TenantID string
	Scope    string
	Value    string
	StreamID string
}

// Uniqueness primitives (ADR 0010). Identical semantics to Postgres;
// SQLite UNIQUE PK gives the same fail-fast guarantee.
func (q *Queries) ClaimUnique(ctx context.Context, arg ClaimUniqueParams) error {
	_, err := q.db.ExecContext(ctx, claimUnique,
		arg.TenantID,
		arg.Scope,
		arg.Value,
		arg.StreamID,
	)
	return err
}

const getUniqueClaim = `-- name: GetUniqueClaim :one
SELECT tenant_id, scope, value, stream_id, claimed_at
FROM unique_claims
WHERE tenant_id = ? AND scope = ? AND value = ?
`

type GetUniqueClaimParams struct {
	TenantID string
	Scope    string
	Value    string
}

func (q *Queries) GetUniqueClaim(ctx context.Context, arg GetUniqueClaimParams) (UniqueClaim, error) {
	row := q.db.QueryRowContext(ctx, getUniqueClaim, arg.TenantID, arg.Scope, arg.Value)
	var i UniqueClaim
	err := row.Scan(
		&i.TenantID,
		&i.Scope,
		&i.Value,
		&i.StreamID,
		&i.ClaimedAt,
	)
	return i, err
}

const releaseUnique = `-- name: ReleaseUnique :exec
DELETE FROM unique_claims
WHERE tenant_id = ? AND scope = ? AND value = ?
`

type ReleaseUniqueParams struct {
	TenantID string
	Scope    string
	Value    string
}

func (q *Queries) ReleaseUnique(ctx context.Context, arg ReleaseUniqueParams) error {
	_, err := q.db.ExecContext(ctx, releaseUnique, arg.TenantID, arg.Scope, arg.Value)
	return err
}
