// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
)

type Event struct {
	EventID           uuid.UUID
	TenantID          string
	StreamID          string
	Version           int64
	GlobalPosition    int64
	TypeUrl           string
	SchemaVersion     int64
	OccurredAt        string
	RecordedAt        string
	CorrelationID     uuid.UUID
	CausationID       uuid.UUID
	CommandID         uuid.UUID
	Actor             string
	ActorPrincipal    string
	Payload           []byte
	PayloadJson       *string
	EncryptionKeyRefs *string
}

type Outbox struct {
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
	EnqueuedAt     string
	PublishedAt    *string
	Attempts       int64
	LastError      *string
	NextAttemptAt  *string
}

type ProcessedEvent struct {
	ProjectionName string
	TenantID       string
	EventID        uuid.UUID
	ProcessedAt    string
}

type ProjectionCheckpoint struct {
	Name      string
	TenantID  string
	Cursor    int64
	UpdatedAt string
}

type ProjectionDlq struct {
	ProjectionName string
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
	TypeUrl        string
	LastError      string
	EnqueuedAt     string
}

type Snapshot struct {
	TenantID           string
	StreamID           string
	Version            int64
	StateSchemaVersion int64
	State              []byte
	CreatedAt          string
}

type StateCache struct {
	TenantID  string
	StreamID  string
	TypeUrl   string
	State     string
	Version   int64
	Terminal  int64
	UpdatedAt string
}

type SubjectKey struct {
	TenantID   string
	Subject    string
	DekWrapped []byte
	KekVersion int64
	CreatedAt  string
	ShreddedAt *string
}

type UniqueClaim struct {
	TenantID  string
	Scope     string
	Value     string
	StreamID  string
	ClaimedAt string
}
