// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const cleanupPublished = `-- name: CleanupPublished :exec
DELETE FROM outbox
WHERE tenant_id = ?
  AND published_at IS NOT NULL
  AND published_at < ?
`

type CleanupPublishedParams struct {
	TenantID    string
	PublishedAt *string
}

func (q *Queries) CleanupPublished(ctx context.Context, arg CleanupPublishedParams) error {
	_, err := q.db.ExecContext(ctx, cleanupPublished, arg.TenantID, arg.PublishedAt)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox
SET attempts   = attempts + 1,
    last_error = ?
WHERE tenant_id = ?
  AND global_position = ?
`

type MarkOutboxFailedParams struct {
	LastError      *string
	TenantID       string
	GlobalPosition int64
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxFailed, arg.LastError, arg.TenantID, arg.GlobalPosition)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox
SET published_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE tenant_id = ?
  AND global_position = ?
`

type MarkOutboxPublishedParams struct {
	TenantID       string
	GlobalPosition int64
}

func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxPublished, arg.TenantID, arg.GlobalPosition)
	return err
}

const pendingOutboxRows = `-- name: PendingOutboxRows :many

SELECT tenant_id, global_position, event_id, enqueued_at, published_at, attempts, last_error
FROM outbox
WHERE tenant_id = ?
  AND published_at IS NULL
ORDER BY global_position
LIMIT ?
`

type PendingOutboxRowsParams struct {
	TenantID string
	Limit    int64
}

// Outbox queries (ADR 0014).
func (q *Queries) PendingOutboxRows(ctx context.Context, arg PendingOutboxRowsParams) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, pendingOutboxRows, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.EnqueuedAt,
			&i.PublishedAt,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingOutboxRowsAllTenants = `-- name: PendingOutboxRowsAllTenants :many
SELECT tenant_id, global_position, event_id, enqueued_at, published_at, attempts, last_error
FROM outbox
WHERE published_at IS NULL
ORDER BY global_position
LIMIT ?
`

func (q *Queries) PendingOutboxRowsAllTenants(ctx context.Context, limit int64) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, pendingOutboxRowsAllTenants, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.EnqueuedAt,
			&i.PublishedAt,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingOutboxWithEnvelope = `-- name: PendingOutboxWithEnvelope :many
SELECT
    o.tenant_id,
    o.global_position,
    o.event_id,
    o.attempts,
    e.stream_id,
    e.version,
    e.type_url,
    e.schema_version,
    e.occurred_at,
    e.recorded_at,
    e.correlation_id,
    e.causation_id,
    e.command_id,
    e.actor,
    e.actor_principal,
    e.payload,
    e.encryption_key_refs
FROM outbox o
JOIN events e
  ON e.tenant_id = o.tenant_id
 AND e.event_id  = o.event_id
WHERE o.published_at IS NULL
ORDER BY o.global_position
LIMIT ?
`

type PendingOutboxWithEnvelopeRow struct {
	TenantID          string
	GlobalPosition    int64
	EventID           uuid.UUID
	Attempts          int64
	StreamID          string
	Version           int64
	TypeUrl           string
	SchemaVersion     int64
	OccurredAt        string
	RecordedAt        string
	CorrelationID     uuid.UUID
	CausationID       uuid.UUID
	CommandID         uuid.UUID
	Actor             string
	ActorPrincipal    string
	Payload           []byte
	EncryptionKeyRefs *string
}

func (q *Queries) PendingOutboxWithEnvelope(ctx context.Context, limit int64) ([]PendingOutboxWithEnvelopeRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingOutboxWithEnvelope, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingOutboxWithEnvelopeRow
	for rows.Next() {
		var i PendingOutboxWithEnvelopeRow
		if err := rows.Scan(
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.Attempts,
			&i.StreamID,
			&i.Version,
			&i.TypeUrl,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.Actor,
			&i.ActorPrincipal,
			&i.Payload,
			&i.EncryptionKeyRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
