// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processed_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const cleanupProcessedEvents = `-- name: CleanupProcessedEvents :execrows
DELETE FROM processed_events
WHERE projection_name = ?
  AND processed_at    < ?
`

type CleanupProcessedEventsParams struct {
	ProjectionName string
	ProcessedAt    string
}

func (q *Queries) CleanupProcessedEvents(ctx context.Context, arg CleanupProcessedEventsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cleanupProcessedEvents, arg.ProjectionName, arg.ProcessedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const hasProcessedEvent = `-- name: HasProcessedEvent :one

SELECT EXISTS (
    SELECT 1 FROM processed_events
    WHERE projection_name = ?
      AND tenant_id       = ?
      AND event_id        = ?
)
`

type HasProcessedEventParams struct {
	ProjectionName string
	TenantID       string
	EventID        uuid.UUID
}

// processed_events queries for SQLite (ADR 0020).
func (q *Queries) HasProcessedEvent(ctx context.Context, arg HasProcessedEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasProcessedEvent, arg.ProjectionName, arg.TenantID, arg.EventID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const markProcessedEvent = `-- name: MarkProcessedEvent :exec
INSERT INTO processed_events (projection_name, tenant_id, event_id, processed_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (projection_name, tenant_id, event_id) DO NOTHING
`

type MarkProcessedEventParams struct {
	ProjectionName string
	TenantID       string
	EventID        uuid.UUID
	ProcessedAt    string
}

func (q *Queries) MarkProcessedEvent(ctx context.Context, arg MarkProcessedEventParams) error {
	_, err := q.db.ExecContext(ctx, markProcessedEvent,
		arg.ProjectionName,
		arg.TenantID,
		arg.EventID,
		arg.ProcessedAt,
	)
	return err
}
