// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projection_checkpoint.sql

package db

import (
	"context"
)

const getProjectionStatus = `-- name: GetProjectionStatus :one
SELECT name, tenant_id, cursor, updated_at
FROM projection_checkpoint
WHERE name      = ?
  AND tenant_id = ?
`

type GetProjectionStatusParams struct {
	Name     string
	TenantID string
}

func (q *Queries) GetProjectionStatus(ctx context.Context, arg GetProjectionStatusParams) (ProjectionCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getProjectionStatus, arg.Name, arg.TenantID)
	var i ProjectionCheckpoint
	err := row.Scan(
		&i.Name,
		&i.TenantID,
		&i.Cursor,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectionCheckpoints = `-- name: ListProjectionCheckpoints :many
SELECT name, tenant_id, cursor, updated_at
FROM projection_checkpoint
ORDER BY name, tenant_id
`

func (q *Queries) ListProjectionCheckpoints(ctx context.Context) ([]ProjectionCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listProjectionCheckpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectionCheckpoint
	for rows.Next() {
		var i ProjectionCheckpoint
		if err := rows.Scan(
			&i.Name,
			&i.TenantID,
			&i.Cursor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadProjectionCheckpoint = `-- name: LoadProjectionCheckpoint :one

SELECT cursor
FROM projection_checkpoint
WHERE name      = ?
  AND tenant_id = ?
`

type LoadProjectionCheckpointParams struct {
	Name     string
	TenantID string
}

// projection_checkpoint queries for SQLite (ADR 0020 Tier 3).
// See the Postgres sibling for the canonical doc comments.
func (q *Queries) LoadProjectionCheckpoint(ctx context.Context, arg LoadProjectionCheckpointParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, loadProjectionCheckpoint, arg.Name, arg.TenantID)
	var cursor int64
	err := row.Scan(&cursor)
	return cursor, err
}

const resetProjectionCheckpoint = `-- name: ResetProjectionCheckpoint :exec
INSERT INTO projection_checkpoint (name, tenant_id, cursor, updated_at)
VALUES (?1, ?2, 0, ?3)
ON CONFLICT (name, tenant_id) DO UPDATE SET
    cursor     = 0,
    updated_at = excluded.updated_at
`

type ResetProjectionCheckpointParams struct {
	Name      string
	TenantID  string
	UpdatedAt string
}

func (q *Queries) ResetProjectionCheckpoint(ctx context.Context, arg ResetProjectionCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, resetProjectionCheckpoint, arg.Name, arg.TenantID, arg.UpdatedAt)
	return err
}

const saveProjectionCheckpoint = `-- name: SaveProjectionCheckpoint :exec
INSERT INTO projection_checkpoint (name, tenant_id, cursor, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (name, tenant_id) DO UPDATE SET
    cursor     = excluded.cursor,
    updated_at = excluded.updated_at
`

type SaveProjectionCheckpointParams struct {
	Name      string
	TenantID  string
	Cursor    int64
	UpdatedAt string
}

func (q *Queries) SaveProjectionCheckpoint(ctx context.Context, arg SaveProjectionCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, saveProjectionCheckpoint,
		arg.Name,
		arg.TenantID,
		arg.Cursor,
		arg.UpdatedAt,
	)
	return err
}

const setProjectionCheckpoint = `-- name: SetProjectionCheckpoint :exec
INSERT INTO projection_checkpoint (name, tenant_id, cursor, updated_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (name, tenant_id) DO UPDATE SET
    cursor     = excluded.cursor,
    updated_at = excluded.updated_at
`

type SetProjectionCheckpointParams struct {
	Name      string
	TenantID  string
	Cursor    int64
	UpdatedAt string
}

func (q *Queries) SetProjectionCheckpoint(ctx context.Context, arg SetProjectionCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, setProjectionCheckpoint,
		arg.Name,
		arg.TenantID,
		arg.Cursor,
		arg.UpdatedAt,
	)
	return err
}
