// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projection_dlq.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const abandonAllProjectionDLQ = `-- name: AbandonAllProjectionDLQ :execrows
DELETE FROM projection_dlq
WHERE projection_name = ?
  AND tenant_id       = ?
`

type AbandonAllProjectionDLQParams struct {
	ProjectionName string
	TenantID       string
}

func (q *Queries) AbandonAllProjectionDLQ(ctx context.Context, arg AbandonAllProjectionDLQParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, abandonAllProjectionDLQ, arg.ProjectionName, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countProjectionDLQ = `-- name: CountProjectionDLQ :one
SELECT COUNT(*) FROM projection_dlq
WHERE projection_name = ?
  AND tenant_id       = ?
`

type CountProjectionDLQParams struct {
	ProjectionName string
	TenantID       string
}

func (q *Queries) CountProjectionDLQ(ctx context.Context, arg CountProjectionDLQParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectionDLQ, arg.ProjectionName, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProjectionDLQ = `-- name: DeleteProjectionDLQ :exec
DELETE FROM projection_dlq
WHERE projection_name = ?
  AND tenant_id       = ?
  AND global_position = ?
`

type DeleteProjectionDLQParams struct {
	ProjectionName string
	TenantID       string
	GlobalPosition int64
}

func (q *Queries) DeleteProjectionDLQ(ctx context.Context, arg DeleteProjectionDLQParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectionDLQ, arg.ProjectionName, arg.TenantID, arg.GlobalPosition)
	return err
}

const insertProjectionDLQ = `-- name: InsertProjectionDLQ :exec

INSERT INTO projection_dlq (
    projection_name, tenant_id, global_position, event_id, type_url, last_error, enqueued_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (projection_name, tenant_id, global_position) DO UPDATE SET
    last_error  = excluded.last_error,
    enqueued_at = excluded.enqueued_at
`

type InsertProjectionDLQParams struct {
	ProjectionName string
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
	TypeUrl        string
	LastError      string
	EnqueuedAt     string
}

// projection_dlq queries for SQLite (ADR 0020).
func (q *Queries) InsertProjectionDLQ(ctx context.Context, arg InsertProjectionDLQParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectionDLQ,
		arg.ProjectionName,
		arg.TenantID,
		arg.GlobalPosition,
		arg.EventID,
		arg.TypeUrl,
		arg.LastError,
		arg.EnqueuedAt,
	)
	return err
}

const listProjectionDLQ = `-- name: ListProjectionDLQ :many
SELECT projection_name, tenant_id, global_position, event_id, type_url, last_error, enqueued_at
FROM projection_dlq
WHERE projection_name = ?1
  AND tenant_id       = ?2
  AND global_position > ?3
ORDER BY global_position
LIMIT ?4
`

type ListProjectionDLQParams struct {
	ProjectionName string
	TenantID       string
	AfterPosition  int64
	MaxRows        int64
}

func (q *Queries) ListProjectionDLQ(ctx context.Context, arg ListProjectionDLQParams) ([]ProjectionDlq, error) {
	rows, err := q.db.QueryContext(ctx, listProjectionDLQ,
		arg.ProjectionName,
		arg.TenantID,
		arg.AfterPosition,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectionDlq
	for rows.Next() {
		var i ProjectionDlq
		if err := rows.Scan(
			&i.ProjectionName,
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.TypeUrl,
			&i.LastError,
			&i.EnqueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
