// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AbandonDLQ(ctx context.Context, arg AbandonDLQParams) error
	// Uniqueness primitives (ADR 0010). Identical semantics to Postgres;
	// SQLite UNIQUE PK gives the same fail-fast guarantee.
	ClaimUnique(ctx context.Context, arg ClaimUniqueParams) error
	CleanupPublished(ctx context.Context, arg CleanupPublishedParams) error
	CountDLQ(ctx context.Context, arg CountDLQParams) (int64, error)
	CountFailing(ctx context.Context, arg CountFailingParams) (int64, error)
	CountPending(ctx context.Context, tenantID string) (int64, error)
	CurrentStreamVersion(ctx context.Context, arg CurrentStreamVersionParams) (interface{}, error)
	DeleteSnapshot(ctx context.Context, arg DeleteSnapshotParams) error
	DeleteStateCacheForType(ctx context.Context, arg DeleteStateCacheForTypeParams) (int64, error)
	DeleteStateCacheForTypeAllTenants(ctx context.Context, typeUrl string) (int64, error)
	ForgetSubject(ctx context.Context, arg ForgetSubjectParams) error
	GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error)
	GetProjectionStatus(ctx context.Context, arg GetProjectionStatusParams) (ProjectionCheckpoint, error)
	// Snapshot queries (ADR 0011).
	GetSnapshot(ctx context.Context, arg GetSnapshotParams) (Snapshot, error)
	GetState(ctx context.Context, arg GetStateParams) (GetStateRow, error)
	// Crypto-shredding subject-key queries (ADR 0010).
	GetSubjectKey(ctx context.Context, arg GetSubjectKeyParams) (SubjectKey, error)
	GetUniqueClaim(ctx context.Context, arg GetUniqueClaimParams) (UniqueClaim, error)
	// Append-path queries for SQLite. Mirror of the Postgres adapter's
	// append.sql, with three dialect deltas:
	//
	//   * No AdvisoryLock. SQLite serializes writers at the file level;
	//     the Append flow in the adapter code skips the AdvisoryLock step.
	//
	//   * global_position is INTEGER PRIMARY KEY AUTOINCREMENT, fetched
	//     via database/sql's Result.LastInsertId() (`:execlastid`) rather
	//     than RETURNING. This avoids a sqlc 1.30 SQLite tokenizer bug
	//     that truncates trailing identifiers in RETURNING clauses.
	//
	//   * recorded_at is passed explicitly by the adapter (set to the
	//     adapter-side clock at append time). The schema's DEFAULT remains
	//     as a safety net for queries that omit it.
	InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error)
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	// ===========================================================================
	// Admin / dashboard queries
	// ===========================================================================
	ListDLQ(ctx context.Context, arg ListDLQParams) ([]ListDLQRow, error)
	ListProjectionCheckpoints(ctx context.Context) ([]ProjectionCheckpoint, error)
	ListShreddedSubjects(ctx context.Context, arg ListShreddedSubjectsParams) ([]ListShreddedSubjectsRow, error)
	ListStates(ctx context.Context, arg ListStatesParams) ([]StateCache, error)
	ListStatesAll(ctx context.Context, arg ListStatesAllParams) ([]StateCache, error)
	// projection_checkpoint queries for SQLite (ADR 0020 Tier 3).
	// See the Postgres sibling for the canonical doc comments.
	LoadProjectionCheckpoint(ctx context.Context, arg LoadProjectionCheckpointParams) (int64, error)
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error
	OldestPendingEnqueuedAt(ctx context.Context, tenantID string) (interface{}, error)
	// Outbox queries (ADR 0014).
	PendingOutboxRows(ctx context.Context, arg PendingOutboxRowsParams) ([]Outbox, error)
	PendingOutboxRowsAllTenants(ctx context.Context, limit int64) ([]Outbox, error)
	// Drain hot path. Filters by retry-readiness, max-attempts (DLQ
	// threshold), and the per-stream "head" rule. The head-versions CTE
	// computes the lowest unpublished, not-yet-DLQ'd version per stream;
	// the outer SELECT then only emits rows that ARE the head. This
	// preserves per-stream order across leader handoffs even when backoff
	// puts the head in cooldown. DLQ'd rows (attempts >= max_attempts)
	// don't appear in the head-versions CTE, so AutoResumeAfterDLQ=true
	// can step past them. AutoResumeAfterDLQ=false uses QuarantinedStreams
	// in the drain runtime for the "DLQ also blocks" semantic.
	PendingOutboxWithEnvelope(ctx context.Context, arg PendingOutboxWithEnvelopeParams) ([]PendingOutboxWithEnvelopeRow, error)
	QuarantinedStreams(ctx context.Context, arg QuarantinedStreamsParams) ([]QuarantinedStreamsRow, error)
	QuarantinedStreamsAllTenants(ctx context.Context, attempts int64) ([]QuarantinedStreamsAllTenantsRow, error)
	ReadAllFromPosition(ctx context.Context, arg ReadAllFromPositionParams) ([]Event, error)
	ReadAllFromPositionTenant(ctx context.Context, arg ReadAllFromPositionTenantParams) ([]Event, error)
	// Read-path queries.
	ReadStream(ctx context.Context, arg ReadStreamParams) ([]Event, error)
	ReadStreamFromVersion(ctx context.Context, arg ReadStreamFromVersionParams) ([]Event, error)
	ReleaseUnique(ctx context.Context, arg ReleaseUniqueParams) error
	ReplayAllDLQ(ctx context.Context, arg ReplayAllDLQParams) (int64, error)
	ReplayDLQ(ctx context.Context, arg ReplayDLQParams) error
	ResetProjectionCheckpoint(ctx context.Context, arg ResetProjectionCheckpointParams) error
	SaveProjectionCheckpoint(ctx context.Context, arg SaveProjectionCheckpointParams) error
	SetProjectionCheckpoint(ctx context.Context, arg SetProjectionCheckpointParams) error
	UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) error
	// state_cache queries for SQLite (ADR 0020 Tier 1).
	// See the Postgres sibling for the canonical doc comments.
	UpsertStateCache(ctx context.Context, arg UpsertStateCacheParams) error
	UpsertSubjectKey(ctx context.Context, arg UpsertSubjectKeyParams) error
}

var _ Querier = (*Queries)(nil)
