// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Uniqueness primitives (ADR 0010). Identical semantics to Postgres;
	// SQLite UNIQUE PK gives the same fail-fast guarantee.
	ClaimUnique(ctx context.Context, arg ClaimUniqueParams) error
	CleanupPublished(ctx context.Context, arg CleanupPublishedParams) error
	CurrentStreamVersion(ctx context.Context, arg CurrentStreamVersionParams) (interface{}, error)
	DeleteSnapshot(ctx context.Context, arg DeleteSnapshotParams) error
	ForgetSubject(ctx context.Context, arg ForgetSubjectParams) error
	GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error)
	// Snapshot queries (ADR 0011).
	GetSnapshot(ctx context.Context, arg GetSnapshotParams) (Snapshot, error)
	// Crypto-shredding subject-key queries (ADR 0010).
	GetSubjectKey(ctx context.Context, arg GetSubjectKeyParams) (SubjectKey, error)
	GetUniqueClaim(ctx context.Context, arg GetUniqueClaimParams) (UniqueClaim, error)
	// Append-path queries for SQLite. Mirror of the Postgres adapter's
	// append.sql, with two dialect deltas:
	//
	//   * No AdvisoryLock — SQLite serializes writers at the file level.
	//     The "no-op" advisory lock exists in the adapter code as a stub
	//     to keep the Append flow uniform across adapters.
	//
	//   * global_position comes from INTEGER PRIMARY KEY AUTOINCREMENT,
	//     not nextval(). The INSERT omits the column; SQLite assigns it
	//     and we read it back via RETURNING.
	//
	// Parameter syntax: bare `?` positional. sqlc 1.30's SQLite engine
	// does not reliably handle `@name` or `sqlc.arg(name)` syntax in our
	// setup, but positional `?` works and sqlc infers parameter struct
	// field names from the column context.
	InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error)
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	ListShreddedSubjects(ctx context.Context, arg ListShreddedSubjectsParams) ([]ListShreddedSubjectsRow, error)
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error
	// Outbox queries (ADR 0014).
	PendingOutboxRows(ctx context.Context, arg PendingOutboxRowsParams) ([]Outbox, error)
	PendingOutboxRowsAllTenants(ctx context.Context, limit int64) ([]Outbox, error)
	PendingOutboxWithEnvelope(ctx context.Context, limit int64) ([]PendingOutboxWithEnvelopeRow, error)
	ReadAllFromPosition(ctx context.Context, arg ReadAllFromPositionParams) ([]Event, error)
	ReadAllFromPositionTenant(ctx context.Context, arg ReadAllFromPositionTenantParams) ([]Event, error)
	// Read-path queries.
	ReadStream(ctx context.Context, arg ReadStreamParams) ([]Event, error)
	ReadStreamFromVersion(ctx context.Context, arg ReadStreamFromVersionParams) ([]Event, error)
	ReleaseUnique(ctx context.Context, arg ReleaseUniqueParams) error
	UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) error
	UpsertSubjectKey(ctx context.Context, arg UpsertSubjectKeyParams) error
}

var _ Querier = (*Queries)(nil)
