// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const currentStreamVersion = `-- name: CurrentStreamVersion :one
SELECT COALESCE(MAX(version), 0) AS current_version
FROM events
WHERE tenant_id = ?
  AND stream_id = ?
`

type CurrentStreamVersionParams struct {
	TenantID string
	StreamID string
}

func (q *Queries) CurrentStreamVersion(ctx context.Context, arg CurrentStreamVersionParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, currentStreamVersion, arg.TenantID, arg.StreamID)
	var current_version interface{}
	err := row.Scan(&current_version)
	return current_version, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    event_id, tenant_id, stream_id, version, global_position,
    type_url, schema_version, occurred_at, recorded_at,
    correlation_id, causation_id, command_id,
    actor, actor_principal, payload, payload_json, encryption_key_refs,
    hash, prev_hash
FROM events
WHERE tenant_id = ?
  AND event_id = ?
`

type GetEventByIDParams struct {
	TenantID string
	EventID  uuid.UUID
}

func (q *Queries) GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, arg.TenantID, arg.EventID)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.TenantID,
		&i.StreamID,
		&i.Version,
		&i.GlobalPosition,
		&i.TypeUrl,
		&i.SchemaVersion,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.CorrelationID,
		&i.CausationID,
		&i.CommandID,
		&i.Actor,
		&i.ActorPrincipal,
		&i.Payload,
		&i.PayloadJson,
		&i.EncryptionKeyRefs,
		&i.Hash,
		&i.PrevHash,
	)
	return i, err
}

const readAllFromPosition = `-- name: ReadAllFromPosition :many
SELECT
    event_id, tenant_id, stream_id, version, global_position,
    type_url, schema_version, occurred_at, recorded_at,
    correlation_id, causation_id, command_id,
    actor, actor_principal, payload, payload_json, encryption_key_refs,
    hash, prev_hash
FROM events
WHERE global_position > ?
ORDER BY global_position
LIMIT ?
`

type ReadAllFromPositionParams struct {
	GlobalPosition int64
	Limit          int64
}

func (q *Queries) ReadAllFromPosition(ctx context.Context, arg ReadAllFromPositionParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, readAllFromPosition, arg.GlobalPosition, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.StreamID,
			&i.Version,
			&i.GlobalPosition,
			&i.TypeUrl,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.Actor,
			&i.ActorPrincipal,
			&i.Payload,
			&i.PayloadJson,
			&i.EncryptionKeyRefs,
			&i.Hash,
			&i.PrevHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readAllFromPositionTenant = `-- name: ReadAllFromPositionTenant :many
SELECT
    event_id, tenant_id, stream_id, version, global_position,
    type_url, schema_version, occurred_at, recorded_at,
    correlation_id, causation_id, command_id,
    actor, actor_principal, payload, payload_json, encryption_key_refs,
    hash, prev_hash
FROM events
WHERE tenant_id = ?
  AND global_position > ?
ORDER BY global_position
LIMIT ?
`

type ReadAllFromPositionTenantParams struct {
	TenantID       string
	GlobalPosition int64
	Limit          int64
}

func (q *Queries) ReadAllFromPositionTenant(ctx context.Context, arg ReadAllFromPositionTenantParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, readAllFromPositionTenant, arg.TenantID, arg.GlobalPosition, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.StreamID,
			&i.Version,
			&i.GlobalPosition,
			&i.TypeUrl,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.Actor,
			&i.ActorPrincipal,
			&i.Payload,
			&i.PayloadJson,
			&i.EncryptionKeyRefs,
			&i.Hash,
			&i.PrevHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readStream = `-- name: ReadStream :many

SELECT
    event_id, tenant_id, stream_id, version, global_position,
    type_url, schema_version, occurred_at, recorded_at,
    correlation_id, causation_id, command_id,
    actor, actor_principal, payload, payload_json, encryption_key_refs,
    hash, prev_hash
FROM events
WHERE tenant_id = ?
  AND stream_id = ?
ORDER BY version
`

type ReadStreamParams struct {
	TenantID string
	StreamID string
}

// Read-path queries.
func (q *Queries) ReadStream(ctx context.Context, arg ReadStreamParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, readStream, arg.TenantID, arg.StreamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.StreamID,
			&i.Version,
			&i.GlobalPosition,
			&i.TypeUrl,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.Actor,
			&i.ActorPrincipal,
			&i.Payload,
			&i.PayloadJson,
			&i.EncryptionKeyRefs,
			&i.Hash,
			&i.PrevHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readStreamFromVersion = `-- name: ReadStreamFromVersion :many
SELECT
    event_id, tenant_id, stream_id, version, global_position,
    type_url, schema_version, occurred_at, recorded_at,
    correlation_id, causation_id, command_id,
    actor, actor_principal, payload, payload_json, encryption_key_refs,
    hash, prev_hash
FROM events
WHERE tenant_id = ?
  AND stream_id = ?
  AND version > ?
ORDER BY version
`

type ReadStreamFromVersionParams struct {
	TenantID string
	StreamID string
	Version  int64
}

func (q *Queries) ReadStreamFromVersion(ctx context.Context, arg ReadStreamFromVersionParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, readStreamFromVersion, arg.TenantID, arg.StreamID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.StreamID,
			&i.Version,
			&i.GlobalPosition,
			&i.TypeUrl,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.Actor,
			&i.ActorPrincipal,
			&i.Payload,
			&i.PayloadJson,
			&i.EncryptionKeyRefs,
			&i.Hash,
			&i.PrevHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
