// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shred.sql

package db

import (
	"context"
)

const forgetSubject = `-- name: ForgetSubject :exec
UPDATE subject_keys
SET dek_wrapped = X'',
    shredded_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE tenant_id = ?
  AND subject = ?
`

type ForgetSubjectParams struct {
	TenantID string
	Subject  string
}

func (q *Queries) ForgetSubject(ctx context.Context, arg ForgetSubjectParams) error {
	_, err := q.db.ExecContext(ctx, forgetSubject, arg.TenantID, arg.Subject)
	return err
}

const getSubjectKey = `-- name: GetSubjectKey :one

SELECT tenant_id, subject, dek_wrapped, kek_version, created_at, shredded_at
FROM subject_keys
WHERE tenant_id = ?
  AND subject = ?
`

type GetSubjectKeyParams struct {
	TenantID string
	Subject  string
}

// Crypto-shredding subject-key queries (ADR 0010).
func (q *Queries) GetSubjectKey(ctx context.Context, arg GetSubjectKeyParams) (SubjectKey, error) {
	row := q.db.QueryRowContext(ctx, getSubjectKey, arg.TenantID, arg.Subject)
	var i SubjectKey
	err := row.Scan(
		&i.TenantID,
		&i.Subject,
		&i.DekWrapped,
		&i.KekVersion,
		&i.CreatedAt,
		&i.ShreddedAt,
	)
	return i, err
}

const listShreddedSubjects = `-- name: ListShreddedSubjects :many
SELECT subject, shredded_at
FROM subject_keys
WHERE tenant_id = ?
  AND shredded_at IS NOT NULL
ORDER BY shredded_at DESC
LIMIT ?
`

type ListShreddedSubjectsParams struct {
	TenantID string
	Limit    int64
}

type ListShreddedSubjectsRow struct {
	Subject    string
	ShreddedAt *string
}

func (q *Queries) ListShreddedSubjects(ctx context.Context, arg ListShreddedSubjectsParams) ([]ListShreddedSubjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listShreddedSubjects, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShreddedSubjectsRow
	for rows.Next() {
		var i ListShreddedSubjectsRow
		if err := rows.Scan(&i.Subject, &i.ShreddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleSubjectKeys = `-- name: ListStaleSubjectKeys :many
SELECT tenant_id, subject, dek_wrapped, kek_version, created_at, shredded_at
FROM subject_keys
WHERE tenant_id    = ?1
  AND kek_version  < ?2
  AND shredded_at IS NULL
ORDER BY subject
LIMIT ?3
`

type ListStaleSubjectKeysParams struct {
	TenantID          string
	CurrentKekVersion int64
	MaxRows           int64
}

func (q *Queries) ListStaleSubjectKeys(ctx context.Context, arg ListStaleSubjectKeysParams) ([]SubjectKey, error) {
	rows, err := q.db.QueryContext(ctx, listStaleSubjectKeys, arg.TenantID, arg.CurrentKekVersion, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubjectKey
	for rows.Next() {
		var i SubjectKey
		if err := rows.Scan(
			&i.TenantID,
			&i.Subject,
			&i.DekWrapped,
			&i.KekVersion,
			&i.CreatedAt,
			&i.ShreddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubjectKey = `-- name: UpsertSubjectKey :exec
INSERT INTO subject_keys (tenant_id, subject, dek_wrapped, kek_version)
VALUES (?, ?, ?, ?)
ON CONFLICT (tenant_id, subject) DO UPDATE SET
    dek_wrapped = excluded.dek_wrapped,
    kek_version = excluded.kek_version
`

type UpsertSubjectKeyParams struct {
	TenantID   string
	Subject    string
	DekWrapped []byte
	KekVersion int64
}

func (q *Queries) UpsertSubjectKey(ctx context.Context, arg UpsertSubjectKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubjectKey,
		arg.TenantID,
		arg.Subject,
		arg.DekWrapped,
		arg.KekVersion,
	)
	return err
}
