// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshot.sql

package db

import (
	"context"
)

const deleteSnapshot = `-- name: DeleteSnapshot :exec
DELETE FROM snapshots
WHERE tenant_id = ?
  AND stream_id = ?
`

type DeleteSnapshotParams struct {
	TenantID string
	StreamID string
}

func (q *Queries) DeleteSnapshot(ctx context.Context, arg DeleteSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, deleteSnapshot, arg.TenantID, arg.StreamID)
	return err
}

const getSnapshot = `-- name: GetSnapshot :one

SELECT tenant_id, stream_id, version, state_schema_version, state, created_at
FROM snapshots
WHERE tenant_id = ?
  AND stream_id = ?
`

type GetSnapshotParams struct {
	TenantID string
	StreamID string
}

// Snapshot queries (ADR 0011).
func (q *Queries) GetSnapshot(ctx context.Context, arg GetSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshot, arg.TenantID, arg.StreamID)
	var i Snapshot
	err := row.Scan(
		&i.TenantID,
		&i.StreamID,
		&i.Version,
		&i.StateSchemaVersion,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSnapshot = `-- name: UpsertSnapshot :exec
INSERT INTO snapshots (tenant_id, stream_id, version, state_schema_version, state)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (tenant_id, stream_id) DO UPDATE SET
    version              = excluded.version,
    state_schema_version = excluded.state_schema_version,
    state                = excluded.state,
    created_at           = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertSnapshotParams struct {
	TenantID           string
	StreamID           string
	Version            int64
	StateSchemaVersion int64
	State              []byte
}

func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertSnapshot,
		arg.TenantID,
		arg.StreamID,
		arg.Version,
		arg.StateSchemaVersion,
		arg.State,
	)
	return err
}
