// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: state_stream.sql

package db

import (
	"context"
)

const countStateStreamLag = `-- name: CountStateStreamLag :one
SELECT
    COUNT(*)                          AS streams_behind,
    COALESCE(MAX(sc.version - COALESCE(p.last_delivered_version, 0)), 0) AS max_lag_versions
FROM state_cache sc
LEFT JOIN state_stream_subscribers p
       ON p.name      = ?1
      AND p.tenant_id = sc.tenant_id
      AND p.stream_id = sc.stream_id
WHERE sc.version > COALESCE(p.last_delivered_version, 0)
  AND (?2 = '' OR sc.tenant_id = ?2)
`

type CountStateStreamLagParams struct {
	Name     string
	TenantID interface{}
}

type CountStateStreamLagRow struct {
	StreamsBehind  int64
	MaxLagVersions interface{}
}

func (q *Queries) CountStateStreamLag(ctx context.Context, arg CountStateStreamLagParams) (CountStateStreamLagRow, error) {
	row := q.db.QueryRowContext(ctx, countStateStreamLag, arg.Name, arg.TenantID)
	var i CountStateStreamLagRow
	err := row.Scan(&i.StreamsBehind, &i.MaxLagVersions)
	return i, err
}

const listStateStreamSubscribers = `-- name: ListStateStreamSubscribers :many
SELECT DISTINCT name FROM state_stream_subscribers ORDER BY name
`

func (q *Queries) ListStateStreamSubscribers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listStateStreamSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamsBehind = `-- name: ListStreamsBehind :many

SELECT
    sc.tenant_id,
    sc.stream_id,
    sc.type_url,
    json(sc.state) AS state,
    sc.version,
    sc.state_schema_version,
    sc.updated_at,
    COALESCE(p.last_delivered_version, 0) AS last_delivered_version
FROM state_cache sc
LEFT JOIN state_stream_subscribers p
       ON p.name      = ?1
      AND p.tenant_id = sc.tenant_id
      AND p.stream_id = sc.stream_id
WHERE sc.version > COALESCE(p.last_delivered_version, 0)
  AND (?2 = '' OR sc.tenant_id = ?2)
ORDER BY sc.updated_at
LIMIT ?3
`

type ListStreamsBehindParams struct {
	Name     string
	TenantID interface{}
	MaxRows  int64
}

type ListStreamsBehindRow struct {
	TenantID             string
	StreamID             string
	TypeUrl              string
	State                interface{}
	Version              int64
	StateSchemaVersion   int64
	UpdatedAt            string
	LastDeliveredVersion int64
}

// state_stream queries for SQLite (ADR 0024).
// json(state) converts the BLOB JSONB back to text bytes so the Go
// side gets the protojson form (ADR 0021).
func (q *Queries) ListStreamsBehind(ctx context.Context, arg ListStreamsBehindParams) ([]ListStreamsBehindRow, error) {
	rows, err := q.db.QueryContext(ctx, listStreamsBehind, arg.Name, arg.TenantID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStreamsBehindRow
	for rows.Next() {
		var i ListStreamsBehindRow
		if err := rows.Scan(
			&i.TenantID,
			&i.StreamID,
			&i.TypeUrl,
			&i.State,
			&i.Version,
			&i.StateSchemaVersion,
			&i.UpdatedAt,
			&i.LastDeliveredVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetStateStreamSubscriber = `-- name: ResetStateStreamSubscriber :execrows
DELETE FROM state_stream_subscribers
WHERE name      = ?1
  AND tenant_id = ?2
`

type ResetStateStreamSubscriberParams struct {
	Name     string
	TenantID string
}

func (q *Queries) ResetStateStreamSubscriber(ctx context.Context, arg ResetStateStreamSubscriberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetStateStreamSubscriber, arg.Name, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetStateStreamSubscriberForStream = `-- name: ResetStateStreamSubscriberForStream :exec
DELETE FROM state_stream_subscribers
WHERE name      = ?1
  AND tenant_id = ?2
  AND stream_id = ?3
`

type ResetStateStreamSubscriberForStreamParams struct {
	Name     string
	TenantID string
	StreamID string
}

func (q *Queries) ResetStateStreamSubscriberForStream(ctx context.Context, arg ResetStateStreamSubscriberForStreamParams) error {
	_, err := q.db.ExecContext(ctx, resetStateStreamSubscriberForStream, arg.Name, arg.TenantID, arg.StreamID)
	return err
}

const upsertStateStreamPosition = `-- name: UpsertStateStreamPosition :exec
INSERT INTO state_stream_subscribers (
    name, tenant_id, stream_id, last_delivered_version, updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
ON CONFLICT (name, tenant_id, stream_id) DO UPDATE SET
    last_delivered_version = MAX(state_stream_subscribers.last_delivered_version, excluded.last_delivered_version),
    updated_at             = excluded.updated_at
`

type UpsertStateStreamPositionParams struct {
	Name      string
	TenantID  string
	StreamID  string
	Version   int64
	UpdatedAt string
}

func (q *Queries) UpsertStateStreamPosition(ctx context.Context, arg UpsertStateStreamPositionParams) error {
	_, err := q.db.ExecContext(ctx, upsertStateStreamPosition,
		arg.Name,
		arg.TenantID,
		arg.StreamID,
		arg.Version,
		arg.UpdatedAt,
	)
	return err
}
