// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: state_cache.sql

package db

import (
	"context"
)

const deleteStateCacheForType = `-- name: DeleteStateCacheForType :execrows
DELETE FROM state_cache
WHERE tenant_id = ?
  AND type_url  = ?
`

type DeleteStateCacheForTypeParams struct {
	TenantID string
	TypeUrl  string
}

func (q *Queries) DeleteStateCacheForType(ctx context.Context, arg DeleteStateCacheForTypeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStateCacheForType, arg.TenantID, arg.TypeUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteStateCacheForTypeAllTenants = `-- name: DeleteStateCacheForTypeAllTenants :execrows
DELETE FROM state_cache
WHERE type_url = ?
`

func (q *Queries) DeleteStateCacheForTypeAllTenants(ctx context.Context, typeUrl string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStateCacheForTypeAllTenants, typeUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getState = `-- name: GetState :one
SELECT type_url, json(state) AS state, version, terminal, state_schema_version, updated_at
FROM state_cache
WHERE tenant_id = ?
  AND stream_id = ?
`

type GetStateParams struct {
	TenantID string
	StreamID string
}

type GetStateRow struct {
	TypeUrl            string
	State              interface{}
	Version            int64
	Terminal           int64
	StateSchemaVersion int64
	UpdatedAt          string
}

// json(state) converts the BLOB JSONB back to text bytes so the Go
// side can unmarshal via protojson without knowing about the binary
// form. The framework's StateCacheReader returns these bytes as []byte.
func (q *Queries) GetState(ctx context.Context, arg GetStateParams) (GetStateRow, error) {
	row := q.db.QueryRowContext(ctx, getState, arg.TenantID, arg.StreamID)
	var i GetStateRow
	err := row.Scan(
		&i.TypeUrl,
		&i.State,
		&i.Version,
		&i.Terminal,
		&i.StateSchemaVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const listStates = `-- name: ListStates :many
SELECT tenant_id, stream_id, type_url, json(state) AS state, version, terminal, state_schema_version, updated_at
FROM state_cache
WHERE tenant_id      = ?1
  AND type_url       = ?2
  AND stream_id      > ?3
ORDER BY stream_id
LIMIT ?4
`

type ListStatesParams struct {
	TenantID      string
	TypeUrl       string
	AfterStreamID string
	MaxRows       int64
}

type ListStatesRow struct {
	TenantID           string
	StreamID           string
	TypeUrl            string
	State              interface{}
	Version            int64
	Terminal           int64
	StateSchemaVersion int64
	UpdatedAt          string
}

func (q *Queries) ListStates(ctx context.Context, arg ListStatesParams) ([]ListStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStates,
		arg.TenantID,
		arg.TypeUrl,
		arg.AfterStreamID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatesRow
	for rows.Next() {
		var i ListStatesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.StreamID,
			&i.TypeUrl,
			&i.State,
			&i.Version,
			&i.Terminal,
			&i.StateSchemaVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatesAll = `-- name: ListStatesAll :many
SELECT tenant_id, stream_id, type_url, json(state) AS state, version, terminal, state_schema_version, updated_at
FROM state_cache
WHERE type_url    = ?1
  AND (tenant_id > ?2
       OR (tenant_id = ?2 AND stream_id > ?3))
ORDER BY tenant_id, stream_id
LIMIT ?4
`

type ListStatesAllParams struct {
	TypeUrl       string
	AfterTenantID string
	AfterStreamID string
	MaxRows       int64
}

type ListStatesAllRow struct {
	TenantID           string
	StreamID           string
	TypeUrl            string
	State              interface{}
	Version            int64
	Terminal           int64
	StateSchemaVersion int64
	UpdatedAt          string
}

func (q *Queries) ListStatesAll(ctx context.Context, arg ListStatesAllParams) ([]ListStatesAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listStatesAll,
		arg.TypeUrl,
		arg.AfterTenantID,
		arg.AfterStreamID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatesAllRow
	for rows.Next() {
		var i ListStatesAllRow
		if err := rows.Scan(
			&i.TenantID,
			&i.StreamID,
			&i.TypeUrl,
			&i.State,
			&i.Version,
			&i.Terminal,
			&i.StateSchemaVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStateCache = `-- name: UpsertStateCache :exec

INSERT INTO state_cache (
    tenant_id, stream_id, type_url, state, version, terminal,
    state_schema_version, updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    jsonb(?4),
    ?5,
    ?6,
    ?7,
    ?8
)
ON CONFLICT (tenant_id, stream_id) DO UPDATE SET
    type_url             = excluded.type_url,
    state                = excluded.state,
    version              = excluded.version,
    terminal             = excluded.terminal,
    state_schema_version = excluded.state_schema_version,
    updated_at           = excluded.updated_at
`

type UpsertStateCacheParams struct {
	TenantID           string
	StreamID           string
	TypeUrl            string
	State              interface{}
	Version            int64
	Terminal           int64
	StateSchemaVersion int64
	UpdatedAt          string
}

// state_cache queries for SQLite (ADR 0020 Tier 1).
// See the Postgres sibling for the canonical doc comments.
// The protojson bytes come in as a TEXT param; jsonb() converts them
// to binary on insert (ADR 0021). Reads return the BLOB; protojson
// on the Go side decodes either form interchangeably.
func (q *Queries) UpsertStateCache(ctx context.Context, arg UpsertStateCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertStateCache,
		arg.TenantID,
		arg.StreamID,
		arg.TypeUrl,
		arg.State,
		arg.Version,
		arg.Terminal,
		arg.StateSchemaVersion,
		arg.UpdatedAt,
	)
	return err
}
