// Restate-mode emission for protoc-gen-es-go. Activated when buf
// invokes the plugin with opt: runtime=restate. The plugin emits
// only Restate service handlers in this mode; the core sum_type /
// codec / projection codegen is skipped.
//
// See ADR 0026 § 3.
package main

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"

	esv1 "github.com/laenenai/eventstore/gen/es/v1"
)

// Import paths the generated Restate-handler code refers to.
var (
	cmdwfPkg     = protogen.GoImportPath("github.com/laenenai/eventstore/cmdworkflow")
	cwrestatePkg = protogen.GoImportPath("github.com/laenenai/eventstore/adapters/cmdworkflow/restate")
	restateSDK   = protogen.GoImportPath("github.com/restatedev/sdk-go")
)

// aggregate captures one State message + its Command sum-type variants.
type aggregate struct {
	name      string             // aggregate short name (e.g., "invoice")
	state     *protogen.Message  // the State message
	commands  []*protogen.Message
	commandSumTypeName string    // the Go interface name (usually "Command")

	// Populated by generateRestateFile before emitRestateService.
	// The Restate-mode file lives in a different Go package; we need
	// the root package path to qualify type references properly.
	rootImport  protogen.GoImportPath
	rootPkgName string
}

// commandVariantInfo records the annotated fields on one command.
type commandVariantInfo struct {
	msg          *protogen.Message
	streamIDFld  *protogen.Field
	tenantIDFld  *protogen.Field
}

// generateRestateFile is called by main.go when runtime=restate is
// configured. Emits handler files; the core sum_type/codec/projection
// emission is skipped in this mode.
func generateRestateFile(plugin *protogen.Plugin, file *protogen.File) error {
	aggregates, err := findAggregatesWithAnnotatedCommands(file)
	if err != nil {
		return err
	}
	if len(aggregates) == 0 {
		return nil
	}

	// The Restate-mode output lives in a DIFFERENT module
	// (adapters/cmdworkflow/restate/gen/...) than the core gen tree.
	// Compute a distinct GoImportPath so protogen properly qualifies
	// references to the core types (Invoice, Command, etc.) with an
	// import alias instead of treating them as same-package.
	//
	// The package name gains a "restate" suffix to avoid the
	// invoicev1-vs-invoicev1 ambiguity at the call site.
	rootImport := string(file.GoImportPath)
	restateImport := protogen.GoImportPath(
		"github.com/laenenai/eventstore/adapters/cmdworkflow/restate/gen" +
			rootImport[len("github.com/laenenai/eventstore/gen"):],
	)
	restatePkgName := string(file.GoPackageName) + "restate"

	out := plugin.NewGeneratedFile(
		file.GeneratedFilenamePrefix+"_restate_es.pb.go",
		restateImport,
	)
	out.P("// Code generated by protoc-gen-es-restate. DO NOT EDIT.")
	out.P("// source: ", file.Desc.Path())
	out.P()
	out.P("package ", restatePkgName)
	out.P()

	// Remember the root import path so emitRestateService can
	// reference Invoice/Command via the root package.
	for _, agg := range aggregates {
		agg.rootImport = file.GoImportPath
		agg.rootPkgName = string(file.GoPackageName)
	}

	for _, agg := range aggregates {
		variants, err := collectVariants(agg)
		if err != nil {
			return err
		}
		emitRestateService(out, agg, variants)
	}
	return nil
}

// findAggregatesWithAnnotatedCommands finds State messages
// (option (es.v1.aggregate) = "X") and pairs them with Command sum
// types in the same file whose variants are annotated.
//
// Skips aggregates whose commands have NO annotations (opt-in).
// Errors if some — but not all — variants have annotations, or if a
// variant has stream_id but not tenant_id (or vice versa).
func findAggregatesWithAnnotatedCommands(file *protogen.File) ([]*aggregate, error) {
	// 1. Collect State messages.
	stateByName := map[string]*aggregate{}
	for _, m := range file.Messages {
		aggName, _ := proto.GetExtension(m.Desc.Options(), esv1.E_Aggregate).(string)
		if aggName == "" {
			continue
		}
		stateByName[aggName] = &aggregate{name: aggName, state: m}
	}
	if len(stateByName) == 0 {
		return nil, nil
	}

	// 2. Find Command sum-type and check variant annotations.
	for _, m := range file.Messages {
		sumName, _ := proto.GetExtension(m.Desc.Options(), esv1.E_SumType).(string)
		if sumName == "" {
			continue
		}
		if len(m.Oneofs) != 1 {
			return nil, fmt.Errorf("%s: sum_type message must have exactly one oneof", m.GoIdent.GoName)
		}
		// Only Command sum-types map to workflow handlers. Skip Event
		// sum-types and arbitrary other sum-types.
		if sumName != "Command" {
			continue
		}

		// Check each variant for annotations. Either ALL have both
		// stream_id + tenant_id, or NONE do (skip whole aggregate).
		anyAnnotated, allAnnotated := false, true
		for _, f := range m.Oneofs[0].Fields {
			variant := f.Message
			if variant == nil {
				return nil, fmt.Errorf("%s.%s: oneof field is not a message variant", m.GoIdent.GoName, f.GoName)
			}
			has := hasStreamID(variant) && hasTenantID(variant)
			if hasStreamID(variant) || hasTenantID(variant) {
				anyAnnotated = true
			}
			if !has {
				allAnnotated = false
			}
		}
		if !anyAnnotated {
			continue // unannotated → no Restate service for this aggregate
		}
		if !allAnnotated {
			// Some annotated, some not — partial. Identify offenders.
			for _, f := range m.Oneofs[0].Fields {
				v := f.Message
				if !hasStreamID(v) {
					return nil, fmt.Errorf("%s: command variant %s is missing a field annotated [(es.v1.stream_id) = true]",
						file.Desc.Path(), v.GoIdent.GoName)
				}
				if !hasTenantID(v) {
					return nil, fmt.Errorf("%s: command variant %s is missing a field annotated [(es.v1.tenant_id) = true]",
						file.Desc.Path(), v.GoIdent.GoName)
				}
			}
		}

		// Locate the aggregate this Command set belongs to. The file
		// must have exactly one aggregate when it has annotated
		// commands — multi-aggregate files would need explicit
		// linking.
		if len(stateByName) > 1 {
			return nil, fmt.Errorf("%s: annotated commands but multiple aggregates declared in one file (%d)",
				file.Desc.Path(), len(stateByName))
		}
		var agg *aggregate
		for _, a := range stateByName {
			agg = a
			break
		}
		agg.commandSumTypeName = sumName
		for _, f := range m.Oneofs[0].Fields {
			agg.commands = append(agg.commands, f.Message)
		}
	}

	// 3. Return aggregates that actually have commands attached.
	var out []*aggregate
	for _, a := range stateByName {
		if len(a.commands) > 0 {
			out = append(out, a)
		}
	}
	return out, nil
}

// collectVariants resolves each command variant to its annotated
// stream_id + tenant_id fields. Called after validation, so missing
// annotations are a bug, not user error.
func collectVariants(agg *aggregate) ([]commandVariantInfo, error) {
	out := make([]commandVariantInfo, 0, len(agg.commands))
	for _, cmd := range agg.commands {
		info := commandVariantInfo{msg: cmd}
		for _, f := range cmd.Fields {
			if isStreamIDField(f) {
				info.streamIDFld = f
			}
			if isTenantIDField(f) {
				info.tenantIDFld = f
			}
		}
		if info.streamIDFld == nil || info.tenantIDFld == nil {
			return nil, fmt.Errorf("%s: missing annotations (post-validation bug)", cmd.GoIdent.GoName)
		}
		out = append(out, info)
	}
	return out, nil
}

func hasStreamID(m *protogen.Message) bool {
	for _, f := range m.Fields {
		if isStreamIDField(f) {
			return true
		}
	}
	return false
}

func hasTenantID(m *protogen.Message) bool {
	for _, f := range m.Fields {
		if isTenantIDField(f) {
			return true
		}
	}
	return false
}

func isStreamIDField(f *protogen.Field) bool {
	v, _ := proto.GetExtension(f.Desc.Options(), esv1.E_StreamId).(bool)
	return v
}

func isTenantIDField(f *protogen.Field) bool {
	v, _ := proto.GetExtension(f.Desc.Options(), esv1.E_TenantId).(bool)
	return v
}

// emitRestateService writes the RestateService struct + one handler
// per command variant. Each handler is a thin wrapper around
// HandleCmd: build the StreamID from the annotated fields, propagate
// tenant via context, invoke.
func emitRestateService(out *protogen.GeneratedFile, agg *aggregate, variants []commandVariantInfo) {
	// Types defined in the root core gen package — Invoice, Command,
	// Create, MarkPaid, Void — must be qualified through the import.
	stateName := out.QualifiedGoIdent(agg.rootImport.Ident(agg.state.GoIdent.GoName))
	cmdIface := out.QualifiedGoIdent(agg.rootImport.Ident(agg.commandSumTypeName))

	// Framework + adapter references.
	ctxType := out.QualifiedGoIdent(contextPkg.Ident("Context"))
	esWithTenant := out.QualifiedGoIdent(esPkg.Ident("WithTenant"))
	esNewStreamID := out.QualifiedGoIdent(esPkg.Ident("NewStreamID"))
	cmdwfWorkflow := out.QualifiedGoIdent(cmdwfPkg.Ident("Workflow"))
	withContext := out.QualifiedGoIdent(cwrestatePkg.Ident("WithContext"))
	restateCtx := out.QualifiedGoIdent(restateSDK.Ident("Context"))

	svcName := "RestateService"
	out.P("// ", svcName, " exposes the ", stateName, " aggregate as a Restate service.")
	out.P("// One handler per ", cmdIface, " variant; each wraps cmdworkflow.Workflow.HandleCmd")
	out.P("// with the tenant and stream id extracted from the command.")
	out.P("type ", svcName, " struct {")
	out.P("\tWorkflow *", cmdwfWorkflow, "[*", stateName, ", ", cmdIface, "]")
	out.P("}")
	out.P()
	out.P("// New", svcName, " returns a Restate-bindable service backed by wf.")
	out.P("func New", svcName, "(wf *", cmdwfWorkflow, "[*", stateName, ", ", cmdIface, "]) *", svcName, " {")
	out.P("\treturn &", svcName, "{Workflow: wf}")
	out.P("}")
	out.P()
	out.P("// ServiceName overrides the SDK's default reflection name so")
	out.P("// the Restate service URL is /", capitalize(agg.name), "/<handler> regardless of Go type names.")
	out.P("func (*", svcName, ") ServiceName() string { return \"", capitalize(agg.name), "\" }")
	out.P()

	// One method per command variant.
	for _, v := range variants {
		cmdName := out.QualifiedGoIdent(agg.rootImport.Ident(v.msg.GoIdent.GoName))
		streamGetter := "Get" + v.streamIDFld.GoName + "()"
		tenantGetter := "Get" + v.tenantIDFld.GoName + "()"
		bgCtx := out.QualifiedGoIdent(contextPkg.Ident("Background"))
		out.P("func (s *", svcName, ") ", v.msg.GoIdent.GoName, "(ctx ", restateCtx, ", cmd *", cmdName, ") (*", stateName, ", error) {")
		out.P("\ttenant := cmd.", tenantGetter)
		out.P("\tsid, err := ", esNewStreamID, "(tenant, \"", agg.name, "\", cmd.", streamGetter, ")")
		out.P("\tif err != nil { return nil, err }")
		out.P("\tstdCtx := ", withContext, "(", esWithTenant, "(", bgCtx, "(), tenant), ctx)")
		out.P("\treturn s.Workflow.HandleCmd(stdCtx, sid, cmd)")
		out.P("}")
		out.P()
	}

	// Suppress unused-import warnings if a particular template branch
	// didn't reference a package.
	out.P("var _ = ", ctxType, "(nil)")
	out.P()
}

// capitalize returns s with its first rune upper-cased.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	return string(s[0]-32) + s[1:]
}
