// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: append.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const advisoryLock = `-- name: AdvisoryLock :exec

SELECT pg_advisory_xact_lock($1::bigint)
`

// Append-path queries. Used inside a single transaction in the
// following sequence (see ADR 0009):
//
//  1. AdvisoryLock          (serializes all writers store-wide)
//  2. For each constraint:  ClaimUnique  (in constraint.sql)
//  3. For each event:       InsertEvent  (allocates global_position)
//  4. For each event:       InsertOutbox (durable publish backstop)
//  5. COMMIT
//
// Optimistic concurrency is enforced by the events PRIMARY KEY
// (tenant_id, stream_id, version) — a stale read produces a
// unique-violation that the adapter translates to ErrConflict.
// Acquire the store-wide append lock. Auto-releases on commit/rollback.
// The constant is the framework's reserved lock key for this table.
func (q *Queries) AdvisoryLock(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, advisoryLock, lockKey)
	return err
}

const backfillEventHash = `-- name: BackfillEventHash :execrows
UPDATE events
SET hash = $1, prev_hash = $2
WHERE tenant_id = $3 AND event_id = $4 AND hash IS NULL
`

type BackfillEventHashParams struct {
	Hash     []byte
	PrevHash []byte
	TenantID string
	EventID  uuid.UUID
}

// Populate hash + prev_hash for an event whose chain columns are NULL,
// as written by streams that existed before ADR 0028's tamper-evident
// chain migration. The `hash IS NULL` predicate is a safety guard: if
// the row already carries a hash, the UPDATE is a no-op (RowsAffected
// = 0) and the Go wrapper errors out, since overwriting an existing
// hash would silently mask tampering.
func (q *Queries) BackfillEventHash(ctx context.Context, arg BackfillEventHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, backfillEventHash,
		arg.Hash,
		arg.PrevHash,
		arg.TenantID,
		arg.EventID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
    event_id,
    tenant_id,
    stream_id,
    version,
    global_position,
    type_url,
    schema_version,
    occurred_at,
    correlation_id,
    causation_id,
    command_id,
    actor,
    actor_principal,
    payload,
    payload_json,
    encryption_key_refs,
    hash,
    prev_hash
) VALUES (
    $1,
    $2,
    $3,
    $4,
    nextval('events_global_position_seq'),
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
RETURNING global_position, recorded_at
`

type InsertEventParams struct {
	EventID           uuid.UUID
	TenantID          string
	StreamID          string
	Version           int64
	TypeUrl           string
	SchemaVersion     int32
	OccurredAt        time.Time
	CorrelationID     uuid.UUID
	CausationID       uuid.UUID
	CommandID         uuid.UUID
	Actor             json.RawMessage
	ActorPrincipal    string
	Payload           []byte
	PayloadJson       []byte
	EncryptionKeyRefs []byte
	Hash              []byte
	PrevHash          []byte
}

type InsertEventRow struct {
	GlobalPosition int64
	RecordedAt     time.Time
}

// Insert one event, allocating its global_position from the sequence
// under the advisory lock. Returns the assigned position and the DB
// commit timestamp so callers can echo them back on the envelope.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.EventID,
		arg.TenantID,
		arg.StreamID,
		arg.Version,
		arg.TypeUrl,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.CorrelationID,
		arg.CausationID,
		arg.CommandID,
		arg.Actor,
		arg.ActorPrincipal,
		arg.Payload,
		arg.PayloadJson,
		arg.EncryptionKeyRefs,
		arg.Hash,
		arg.PrevHash,
	)
	var i InsertEventRow
	err := row.Scan(&i.GlobalPosition, &i.RecordedAt)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (tenant_id, global_position, event_id)
VALUES ($1, $2, $3)
`

type InsertOutboxParams struct {
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
}

// Insert the outbox row for an event. The drain process polls
// outbox_pending_idx and hands rows to the configured EventPublisher.
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.TenantID, arg.GlobalPosition, arg.EventID)
	return err
}

const lastStreamHash = `-- name: LastStreamHash :one
SELECT hash FROM events
WHERE tenant_id = $1 AND stream_id = $2
ORDER BY version DESC
LIMIT 1
`

type LastStreamHashParams struct {
	TenantID string
	StreamID string
}

// Returns the hash of the most recent event in a stream, used to
// chain the next append. Empty result for streams with no events.
func (q *Queries) LastStreamHash(ctx context.Context, arg LastStreamHashParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, lastStreamHash, arg.TenantID, arg.StreamID)
	var hash []byte
	err := row.Scan(&hash)
	return hash, err
}
