// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: append.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advisoryLock = `-- name: AdvisoryLock :exec

SELECT pg_advisory_xact_lock($1::bigint)
`

// Append-path queries. Used inside a single transaction in the
// following sequence (see ADR 0009):
//
//  1. AdvisoryLock          (serializes all writers store-wide)
//  2. For each constraint:  ClaimUnique  (in constraint.sql)
//  3. For each event:       InsertEvent  (allocates global_position)
//  4. For each event:       InsertOutbox (durable publish backstop)
//  5. COMMIT
//
// Optimistic concurrency is enforced by the events PRIMARY KEY
// (tenant_id, stream_id, version) — a stale read produces a
// unique-violation that the adapter translates to ErrConflict.
// Acquire the store-wide append lock. Auto-releases on commit/rollback.
// The constant is the framework's reserved lock key for this table.
func (q *Queries) AdvisoryLock(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, advisoryLock, lockKey)
	return err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
    event_id,
    tenant_id,
    stream_id,
    version,
    global_position,
    type_url,
    schema_version,
    occurred_at,
    correlation_id,
    causation_id,
    command_id,
    actor,
    actor_principal,
    payload,
    payload_json,
    encryption_key_refs
) VALUES (
    $1,
    $2,
    $3,
    $4,
    nextval('events_global_position_seq'),
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING global_position, recorded_at
`

type InsertEventParams struct {
	EventID           uuid.UUID
	TenantID          string
	StreamID          string
	Version           int64
	TypeUrl           string
	SchemaVersion     int32
	OccurredAt        time.Time
	CorrelationID     uuid.UUID
	CausationID       uuid.UUID
	CommandID         uuid.UUID
	Actor             []byte
	ActorPrincipal    string
	Payload           []byte
	PayloadJson       []byte
	EncryptionKeyRefs []byte
}

type InsertEventRow struct {
	GlobalPosition int64
	RecordedAt     time.Time
}

// Insert one event, allocating its global_position from the sequence
// under the advisory lock. Returns the assigned position and the DB
// commit timestamp so callers can echo them back on the envelope.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.EventID,
		arg.TenantID,
		arg.StreamID,
		arg.Version,
		arg.TypeUrl,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.CorrelationID,
		arg.CausationID,
		arg.CommandID,
		arg.Actor,
		arg.ActorPrincipal,
		arg.Payload,
		arg.PayloadJson,
		arg.EncryptionKeyRefs,
	)
	var i InsertEventRow
	err := row.Scan(&i.GlobalPosition, &i.RecordedAt)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (tenant_id, global_position, event_id)
VALUES ($1, $2, $3)
`

type InsertOutboxParams struct {
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
}

// Insert the outbox row for an event. The drain process polls
// outbox_pending_idx and hands rows to the configured EventPublisher.
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.TenantID, arg.GlobalPosition, arg.EventID)
	return err
}
