// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: constraint.sql

package db

import (
	"context"
)

const claimUnique = `-- name: ClaimUnique :exec

INSERT INTO unique_claims (tenant_id, scope, value, stream_id)
VALUES ($1, $2, $3, $4)
`

type ClaimUniqueParams struct {
	TenantID string
	Scope    string
	Value    string
	StreamID string
}

// First-class uniqueness primitives (ADR 0010).
//
// A claim is inserted in the same transaction as the events that produce
// it. The UNIQUE(tenant_id, scope, value) PK enforces transactional
// uniqueness — a conflict fails the entire append, which the adapter
// translates to ErrConstraintViolated.
//
// Cross-tenant uniqueness uses tenant_id = '__global__' explicitly; the
// framework refuses to set this implicitly.
func (q *Queries) ClaimUnique(ctx context.Context, arg ClaimUniqueParams) error {
	_, err := q.db.Exec(ctx, claimUnique,
		arg.TenantID,
		arg.Scope,
		arg.Value,
		arg.StreamID,
	)
	return err
}

const getUniqueClaim = `-- name: GetUniqueClaim :one
SELECT tenant_id, scope, value, stream_id, claimed_at FROM unique_claims
WHERE tenant_id = $1 AND scope = $2 AND value = $3
`

type GetUniqueClaimParams struct {
	TenantID string
	Scope    string
	Value    string
}

func (q *Queries) GetUniqueClaim(ctx context.Context, arg GetUniqueClaimParams) (UniqueClaim, error) {
	row := q.db.QueryRow(ctx, getUniqueClaim, arg.TenantID, arg.Scope, arg.Value)
	var i UniqueClaim
	err := row.Scan(
		&i.TenantID,
		&i.Scope,
		&i.Value,
		&i.StreamID,
		&i.ClaimedAt,
	)
	return i, err
}

const releaseUnique = `-- name: ReleaseUnique :exec
DELETE FROM unique_claims
WHERE tenant_id = $1 AND scope = $2 AND value = $3
`

type ReleaseUniqueParams struct {
	TenantID string
	Scope    string
	Value    string
}

func (q *Queries) ReleaseUnique(ctx context.Context, arg ReleaseUniqueParams) error {
	_, err := q.db.Exec(ctx, releaseUnique, arg.TenantID, arg.Scope, arg.Value)
	return err
}
