// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Event struct {
	EventID           uuid.UUID
	TenantID          string
	StreamID          string
	Version           int64
	GlobalPosition    int64
	TypeUrl           string
	SchemaVersion     int32
	OccurredAt        time.Time
	RecordedAt        time.Time
	CorrelationID     uuid.UUID
	CausationID       uuid.UUID
	CommandID         uuid.UUID
	Actor             json.RawMessage
	ActorPrincipal    string
	Payload           []byte
	PayloadJson       []byte
	EncryptionKeyRefs []byte
}

type Outbox struct {
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
	EnqueuedAt     time.Time
	PublishedAt    *time.Time
	Attempts       int32
	LastError      *string
	NextAttemptAt  *time.Time
}

type ProcessedEvent struct {
	ProjectionName string
	TenantID       string
	EventID        uuid.UUID
	ProcessedAt    time.Time
}

type ProjectionCheckpoint struct {
	Name      string
	TenantID  string
	Cursor    int64
	UpdatedAt time.Time
}

type ProjectionDlq struct {
	ProjectionName string
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
	TypeUrl        string
	LastError      string
	EnqueuedAt     time.Time
}

type Snapshot struct {
	TenantID           string
	StreamID           string
	Version            int64
	StateSchemaVersion int32
	State              []byte
	CreatedAt          time.Time
}

type StateCache struct {
	TenantID           string
	StreamID           string
	TypeUrl            string
	State              json.RawMessage
	Version            int64
	Terminal           bool
	UpdatedAt          time.Time
	StateSchemaVersion int32
}

type StateStreamSubscriber struct {
	Name                 string
	TenantID             string
	StreamID             string
	LastDeliveredVersion int64
	UpdatedAt            time.Time
}

type SubjectKey struct {
	TenantID   string
	Subject    string
	DekWrapped []byte
	KekVersion int32
	CreatedAt  time.Time
	ShreddedAt *time.Time
}

type SubscriberDlq struct {
	SubscriberName string
	TenantID       string
	EventID        string
	StreamID       string
	TypeUrl        string
	LastError      string
	Attempts       int32
	EnqueuedAt     time.Time
}

type UniqueClaim struct {
	TenantID  string
	Scope     string
	Value     string
	StreamID  string
	ClaimedAt time.Time
}
