// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Event struct {
	EventID           uuid.UUID
	TenantID          string
	StreamID          string
	Version           int64
	GlobalPosition    int64
	TypeUrl           string
	SchemaVersion     int32
	OccurredAt        time.Time
	RecordedAt        time.Time
	CorrelationID     uuid.UUID
	CausationID       uuid.UUID
	CommandID         uuid.UUID
	Actor             []byte
	ActorPrincipal    string
	Payload           []byte
	PayloadJson       []byte
	EncryptionKeyRefs []byte
}

type Outbox struct {
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
	EnqueuedAt     time.Time
	PublishedAt    *time.Time
	Attempts       int32
	LastError      *string
}

type Snapshot struct {
	TenantID           string
	StreamID           string
	Version            int64
	StateSchemaVersion int32
	State              []byte
	CreatedAt          time.Time
}

type SubjectKey struct {
	TenantID   string
	Subject    string
	DekWrapped []byte
	KekVersion int32
	CreatedAt  time.Time
	ShreddedAt *time.Time
}

type UniqueClaim struct {
	TenantID  string
	Scope     string
	Value     string
	StreamID  string
	ClaimedAt time.Time
}
