// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanupPublished = `-- name: CleanupPublished :exec
DELETE FROM outbox
WHERE tenant_id = $1
  AND published_at IS NOT NULL
  AND published_at < $2
`

type CleanupPublishedParams struct {
	TenantID  string
	OlderThan *time.Time
}

// Retention pruning. Deletes rows that have been published longer than
// @older_than. Runs in the same scheduled wake-up as the publish drain.
func (q *Queries) CleanupPublished(ctx context.Context, arg CleanupPublishedParams) error {
	_, err := q.db.Exec(ctx, cleanupPublished, arg.TenantID, arg.OlderThan)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox
SET attempts   = attempts + 1,
    last_error = $1
WHERE tenant_id = $2
  AND global_position = $3
`

type MarkOutboxFailedParams struct {
	LastError      *string
	TenantID       string
	GlobalPosition int64
}

// Increment attempts and record the error. The next drain run retries;
// exponential backoff is the publisher's concern, not the outbox's.
func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.LastError, arg.TenantID, arg.GlobalPosition)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox
SET published_at = clock_timestamp()
WHERE tenant_id = $1
  AND global_position = $2
`

type MarkOutboxPublishedParams struct {
	TenantID       string
	GlobalPosition int64
}

func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, arg.TenantID, arg.GlobalPosition)
	return err
}

const pendingOutboxRows = `-- name: PendingOutboxRows :many

SELECT tenant_id, global_position, event_id, enqueued_at, published_at, attempts, last_error
FROM outbox
WHERE tenant_id = $1
  AND published_at IS NULL
ORDER BY global_position
LIMIT $2
`

type PendingOutboxRowsParams struct {
	TenantID string
	MaxRows  int32
}

// Outbox queries (ADR 0014).
//
// The drain process wakes the database on a schedule, pulls pending
// rows in global_position order, fetches the envelope+payload via a
// JOIN to events, hands off to the EventPublisher, then marks each row
// published. The same wake-up also runs the cleanup pass.
// Tenant-scoped pending rows. Hot path for per-tenant publishers.
func (q *Queries) PendingOutboxRows(ctx context.Context, arg PendingOutboxRowsParams) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, pendingOutboxRows, arg.TenantID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.EnqueuedAt,
			&i.PublishedAt,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingOutboxRowsAllTenants = `-- name: PendingOutboxRowsAllTenants :many
SELECT tenant_id, global_position, event_id, enqueued_at, published_at, attempts, last_error
FROM outbox
WHERE published_at IS NULL
ORDER BY global_position
LIMIT $1
`

// Cross-tenant pending rows. Used by the shared scheduled drain that
// handles all tenants in one wake-up.
func (q *Queries) PendingOutboxRowsAllTenants(ctx context.Context, maxRows int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, pendingOutboxRowsAllTenants, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.EnqueuedAt,
			&i.PublishedAt,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingOutboxWithEnvelope = `-- name: PendingOutboxWithEnvelope :many
SELECT
    o.tenant_id,
    o.global_position,
    o.event_id,
    o.attempts,
    e.stream_id,
    e.version,
    e.type_url,
    e.schema_version,
    e.occurred_at,
    e.recorded_at,
    e.correlation_id,
    e.causation_id,
    e.command_id,
    e.actor,
    e.actor_principal,
    e.payload,
    e.encryption_key_refs
FROM outbox o
JOIN events e
  ON e.tenant_id = o.tenant_id
 AND e.event_id  = o.event_id
WHERE o.published_at IS NULL
ORDER BY o.global_position
LIMIT $1
`

type PendingOutboxWithEnvelopeRow struct {
	TenantID          string
	GlobalPosition    int64
	EventID           uuid.UUID
	Attempts          int32
	StreamID          string
	Version           int64
	TypeUrl           string
	SchemaVersion     int32
	OccurredAt        time.Time
	RecordedAt        time.Time
	CorrelationID     uuid.UUID
	CausationID       uuid.UUID
	CommandID         uuid.UUID
	Actor             []byte
	ActorPrincipal    string
	Payload           []byte
	EncryptionKeyRefs []byte
}

// Drain hot path: pending rows joined to their envelope+payload, ready
// to hand to the publisher.
func (q *Queries) PendingOutboxWithEnvelope(ctx context.Context, maxRows int32) ([]PendingOutboxWithEnvelopeRow, error) {
	rows, err := q.db.Query(ctx, pendingOutboxWithEnvelope, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingOutboxWithEnvelopeRow
	for rows.Next() {
		var i PendingOutboxWithEnvelopeRow
		if err := rows.Scan(
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.Attempts,
			&i.StreamID,
			&i.Version,
			&i.TypeUrl,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.Actor,
			&i.ActorPrincipal,
			&i.Payload,
			&i.EncryptionKeyRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
