// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const abandonDLQ = `-- name: AbandonDLQ :exec
UPDATE outbox
SET published_at = clock_timestamp(),
    last_error   = COALESCE(last_error, '') || ' [abandoned]'
WHERE tenant_id      = $1
  AND global_position = $2
  AND published_at IS NULL
`

type AbandonDLQParams struct {
	TenantID       string
	GlobalPosition int64
}

// Mark a DLQ'd row as published (set published_at = now) without
// actually publishing. Use when an event is genuinely garbage. The
// event itself stays in the events table (ADR 0005); only the
// outbox row is closed.
func (q *Queries) AbandonDLQ(ctx context.Context, arg AbandonDLQParams) error {
	_, err := q.db.Exec(ctx, abandonDLQ, arg.TenantID, arg.GlobalPosition)
	return err
}

const cleanupPublished = `-- name: CleanupPublished :exec
DELETE FROM outbox
WHERE tenant_id = $1
  AND published_at IS NOT NULL
  AND published_at < $2
`

type CleanupPublishedParams struct {
	TenantID  string
	OlderThan *time.Time
}

// Retention pruning. Deletes rows that have been published longer
// than @older_than. Runs in the same scheduled wake-up as the
// publish drain.
func (q *Queries) CleanupPublished(ctx context.Context, arg CleanupPublishedParams) error {
	_, err := q.db.Exec(ctx, cleanupPublished, arg.TenantID, arg.OlderThan)
	return err
}

const countDLQ = `-- name: CountDLQ :one
SELECT COUNT(*)::bigint
FROM outbox
WHERE tenant_id    = $1
  AND published_at IS NULL
  AND attempts    >= $2
`

type CountDLQParams struct {
	TenantID    string
	MaxAttempts int32
}

// Count of rows in DLQ state. Gauge metric.
func (q *Queries) CountDLQ(ctx context.Context, arg CountDLQParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDLQ, arg.TenantID, arg.MaxAttempts)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFailing = `-- name: CountFailing :one
SELECT COUNT(*)::bigint
FROM outbox
WHERE tenant_id    = $1
  AND published_at IS NULL
  AND attempts     > 0
  AND attempts     < $2
`

type CountFailingParams struct {
	TenantID    string
	MaxAttempts int32
}

// Rows that have failed at least once but not yet hit DLQ.
// Worth watching but not alarming.
func (q *Queries) CountFailing(ctx context.Context, arg CountFailingParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFailing, arg.TenantID, arg.MaxAttempts)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPending = `-- name: CountPending :one
SELECT COUNT(*)::bigint
FROM outbox
WHERE tenant_id    = $1
  AND published_at IS NULL
`

// Total pending (unpublished) rows. Gauge metric.
func (q *Queries) CountPending(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPending, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listDLQ = `-- name: ListDLQ :many

SELECT
    o.tenant_id,
    o.global_position,
    o.event_id,
    o.enqueued_at,
    o.attempts,
    o.last_error,
    o.next_attempt_at,
    e.stream_id,
    e.type_url,
    e.correlation_id,
    e.causation_id,
    e.command_id,
    e.actor_principal
FROM outbox o
JOIN events e
  ON e.tenant_id = o.tenant_id
 AND e.event_id  = o.event_id
WHERE o.tenant_id      = $1
  AND o.published_at IS NULL
  AND o.attempts     >= $2
  AND o.global_position > $3
ORDER BY o.global_position
LIMIT $4
`

type ListDLQParams struct {
	TenantID      string
	MaxAttempts   int32
	AfterPosition int64
	MaxRows       int32
}

type ListDLQRow struct {
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
	EnqueuedAt     time.Time
	Attempts       int32
	LastError      *string
	NextAttemptAt  *time.Time
	StreamID       string
	TypeUrl        string
	CorrelationID  uuid.UUID
	CausationID    uuid.UUID
	CommandID      uuid.UUID
	ActorPrincipal string
}

// ===========================================================================
// Admin / dashboard queries
// ===========================================================================
// Paginated listing of rows in DLQ state (attempts >= @max_attempts
// AND not yet published). Pass the global_position of the last row
// in the previous page as @after_position to fetch the next page;
// start with @after_position = 0.
func (q *Queries) ListDLQ(ctx context.Context, arg ListDLQParams) ([]ListDLQRow, error) {
	rows, err := q.db.Query(ctx, listDLQ,
		arg.TenantID,
		arg.MaxAttempts,
		arg.AfterPosition,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDLQRow
	for rows.Next() {
		var i ListDLQRow
		if err := rows.Scan(
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.EnqueuedAt,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.StreamID,
			&i.TypeUrl,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.ActorPrincipal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox
SET attempts        = attempts + 1,
    last_error      = $1,
    next_attempt_at = $2
WHERE tenant_id      = $3
  AND global_position = $4
`

type MarkOutboxFailedParams struct {
	LastError      *string
	NextAttemptAt  *time.Time
	TenantID       string
	GlobalPosition int64
}

// Increment attempts, record the last error, and set the next
// retry-eligible time. The Drain computes next_attempt_at via its
// backoff function and passes it in.
func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed,
		arg.LastError,
		arg.NextAttemptAt,
		arg.TenantID,
		arg.GlobalPosition,
	)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox
SET published_at = clock_timestamp()
WHERE tenant_id = $1
  AND global_position = $2
`

type MarkOutboxPublishedParams struct {
	TenantID       string
	GlobalPosition int64
}

func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, arg.TenantID, arg.GlobalPosition)
	return err
}

const oldestPendingEnqueuedAt = `-- name: OldestPendingEnqueuedAt :one
SELECT MIN(enqueued_at)::timestamptz
FROM outbox
WHERE tenant_id    = $1
  AND published_at IS NULL
`

// Returns the earliest enqueued_at among pending rows, or NULL if
// the pending set is empty. Compute lag = now() - this in app code.
func (q *Queries) OldestPendingEnqueuedAt(ctx context.Context, tenantID string) (time.Time, error) {
	row := q.db.QueryRow(ctx, oldestPendingEnqueuedAt, tenantID)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const pendingOutboxRows = `-- name: PendingOutboxRows :many

SELECT tenant_id, global_position, event_id, enqueued_at, published_at, attempts, last_error, next_attempt_at
FROM outbox
WHERE tenant_id = $1
  AND published_at IS NULL
ORDER BY global_position
LIMIT $2
`

type PendingOutboxRowsParams struct {
	TenantID string
	MaxRows  int32
}

// Outbox queries (ADR 0014).
//
// The drain process wakes the database on a schedule, pulls pending
// rows in global_position order, fetches the envelope+payload via a
// JOIN to events, hands off to the EventPublisher, then marks each row
// published. The same wake-up also runs the cleanup pass.
// Tenant-scoped pending rows. Hot path for per-tenant publishers.
func (q *Queries) PendingOutboxRows(ctx context.Context, arg PendingOutboxRowsParams) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, pendingOutboxRows, arg.TenantID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.EnqueuedAt,
			&i.PublishedAt,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingOutboxRowsAllTenants = `-- name: PendingOutboxRowsAllTenants :many
SELECT tenant_id, global_position, event_id, enqueued_at, published_at, attempts, last_error, next_attempt_at
FROM outbox
WHERE published_at IS NULL
ORDER BY global_position
LIMIT $1
`

// Cross-tenant pending rows. Used by the shared scheduled drain that
// handles all tenants in one wake-up.
func (q *Queries) PendingOutboxRowsAllTenants(ctx context.Context, maxRows int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, pendingOutboxRowsAllTenants, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.EnqueuedAt,
			&i.PublishedAt,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingOutboxWithEnvelope = `-- name: PendingOutboxWithEnvelope :many
SELECT
    o.tenant_id,
    o.global_position,
    o.event_id,
    o.attempts,
    e.stream_id,
    e.version,
    e.type_url,
    e.schema_version,
    e.occurred_at,
    e.recorded_at,
    e.correlation_id,
    e.causation_id,
    e.command_id,
    e.actor,
    e.actor_principal,
    e.payload,
    e.encryption_key_refs,
    e.hash,
    e.prev_hash
FROM outbox o
JOIN events e
  ON e.tenant_id = o.tenant_id
 AND e.event_id  = o.event_id
WHERE o.published_at IS NULL
  AND (o.next_attempt_at IS NULL OR o.next_attempt_at <= $1)
  AND o.attempts < $2
  AND NOT EXISTS (
    SELECT 1
    FROM outbox o2
    JOIN events e2
      ON e2.tenant_id = o2.tenant_id
     AND e2.event_id  = o2.event_id
    WHERE e2.tenant_id = e.tenant_id
      AND e2.stream_id = e.stream_id
      AND e2.version   < e.version
      AND o2.published_at IS NULL
      AND o2.attempts < $2
  )
ORDER BY o.global_position
LIMIT $3
`

type PendingOutboxWithEnvelopeParams struct {
	Now         *time.Time
	MaxAttempts int32
	MaxRows     int32
}

type PendingOutboxWithEnvelopeRow struct {
	TenantID          string
	GlobalPosition    int64
	EventID           uuid.UUID
	Attempts          int32
	StreamID          string
	Version           int64
	TypeUrl           string
	SchemaVersion     int32
	OccurredAt        time.Time
	RecordedAt        time.Time
	CorrelationID     uuid.UUID
	CausationID       uuid.UUID
	CommandID         uuid.UUID
	Actor             json.RawMessage
	ActorPrincipal    string
	Payload           []byte
	EncryptionKeyRefs []byte
	Hash              []byte
	PrevHash          []byte
}

// Drain hot path: pending rows joined to their envelope+payload,
// filtered by retry-readiness, max-attempts (DLQ threshold), and the
// per-stream "head" rule. The head rule (NOT EXISTS subquery) blocks
// any row whose stream has a lower-version unpublished, not-yet-DLQ'd
// row — preserving per-stream order even across leader handoffs when
// backoff puts the head in cooldown. DLQ'd rows (attempts >=
// @max_attempts) don't block, so the AutoResumeAfterDLQ=true path can
// step past them. The DLQ-quarantines-stream semantic
// (AutoResumeAfterDLQ=false) is layered on by the drain via
// QuarantinedStreams, not by this query.
func (q *Queries) PendingOutboxWithEnvelope(ctx context.Context, arg PendingOutboxWithEnvelopeParams) ([]PendingOutboxWithEnvelopeRow, error) {
	rows, err := q.db.Query(ctx, pendingOutboxWithEnvelope, arg.Now, arg.MaxAttempts, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingOutboxWithEnvelopeRow
	for rows.Next() {
		var i PendingOutboxWithEnvelopeRow
		if err := rows.Scan(
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.Attempts,
			&i.StreamID,
			&i.Version,
			&i.TypeUrl,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.Actor,
			&i.ActorPrincipal,
			&i.Payload,
			&i.EncryptionKeyRefs,
			&i.Hash,
			&i.PrevHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quarantinedStreams = `-- name: QuarantinedStreams :many
SELECT DISTINCT o.tenant_id, e.stream_id
FROM outbox o
JOIN events e
  ON e.tenant_id = o.tenant_id
 AND e.event_id  = o.event_id
WHERE o.published_at IS NULL
  AND o.attempts >= $1
  AND o.tenant_id = $2
`

type QuarantinedStreamsParams struct {
	MaxAttempts int32
	TenantID    string
}

type QuarantinedStreamsRow struct {
	TenantID string
	StreamID string
}

// Returns the distinct (tenant_id, stream_id) pairs that have at
// least one outbox row in DLQ state (attempts >= max_attempts AND
// published_at IS NULL). The drain uses this to skip ALL rows of a
// stream once any row enters DLQ, preserving per-stream order
// (no gap delivery without operator intervention).
func (q *Queries) QuarantinedStreams(ctx context.Context, arg QuarantinedStreamsParams) ([]QuarantinedStreamsRow, error) {
	rows, err := q.db.Query(ctx, quarantinedStreams, arg.MaxAttempts, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuarantinedStreamsRow
	for rows.Next() {
		var i QuarantinedStreamsRow
		if err := rows.Scan(&i.TenantID, &i.StreamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quarantinedStreamsAllTenants = `-- name: QuarantinedStreamsAllTenants :many
SELECT DISTINCT o.tenant_id, e.stream_id
FROM outbox o
JOIN events e
  ON e.tenant_id = o.tenant_id
 AND e.event_id  = o.event_id
WHERE o.published_at IS NULL
  AND o.attempts >= $1
`

type QuarantinedStreamsAllTenantsRow struct {
	TenantID string
	StreamID string
}

func (q *Queries) QuarantinedStreamsAllTenants(ctx context.Context, maxAttempts int32) ([]QuarantinedStreamsAllTenantsRow, error) {
	rows, err := q.db.Query(ctx, quarantinedStreamsAllTenants, maxAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuarantinedStreamsAllTenantsRow
	for rows.Next() {
		var i QuarantinedStreamsAllTenantsRow
		if err := rows.Scan(&i.TenantID, &i.StreamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replayAllDLQ = `-- name: ReplayAllDLQ :execrows
UPDATE outbox
SET attempts        = 0,
    next_attempt_at = NULL,
    last_error      = NULL
WHERE tenant_id    = $1
  AND published_at IS NULL
  AND attempts    >= $2
`

type ReplayAllDLQParams struct {
	TenantID    string
	MaxAttempts int32
}

// Bulk-replay every DLQ'd row for a tenant. Useful after a
// publisher outage recovery. Returns the number of rows reset.
func (q *Queries) ReplayAllDLQ(ctx context.Context, arg ReplayAllDLQParams) (int64, error) {
	result, err := q.db.Exec(ctx, replayAllDLQ, arg.TenantID, arg.MaxAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replayDLQ = `-- name: ReplayDLQ :exec
UPDATE outbox
SET attempts        = 0,
    next_attempt_at = NULL,
    last_error      = NULL
WHERE tenant_id      = $1
  AND global_position = $2
`

type ReplayDLQParams struct {
	TenantID       string
	GlobalPosition int64
}

// Reset a single row's attempts/backoff so the next drain run picks
// it up. Used by operators after fixing root cause.
func (q *Queries) ReplayDLQ(ctx context.Context, arg ReplayDLQParams) error {
	_, err := q.db.Exec(ctx, replayDLQ, arg.TenantID, arg.GlobalPosition)
	return err
}
