// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processed_events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanupProcessedEvents = `-- name: CleanupProcessedEvents :execrows
DELETE FROM processed_events
WHERE projection_name = $1
  AND processed_at < $2
`

type CleanupProcessedEventsParams struct {
	ProjectionName string
	OlderThan      time.Time
}

// Retention pruning. Deletes processed_events rows older than
// @older_than. Returns the number of rows deleted. Operators run this
// periodically since the table grows monotonically with event count.
func (q *Queries) CleanupProcessedEvents(ctx context.Context, arg CleanupProcessedEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupProcessedEvents, arg.ProjectionName, arg.OlderThan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hasProcessedEvent = `-- name: HasProcessedEvent :one

SELECT EXISTS (
    SELECT 1 FROM processed_events
    WHERE projection_name = $1
      AND tenant_id       = $2
      AND event_id        = $3
)
`

type HasProcessedEventParams struct {
	ProjectionName string
	TenantID       string
	EventID        uuid.UUID
}

// processed_events queries (ADR 0020 — WithDedup escape hatch).
// Returns true if (projection_name, tenant_id, event_id) is already
// recorded. The wrapper checks this before invoking the inner handler.
func (q *Queries) HasProcessedEvent(ctx context.Context, arg HasProcessedEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasProcessedEvent, arg.ProjectionName, arg.TenantID, arg.EventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markProcessedEvent = `-- name: MarkProcessedEvent :exec
INSERT INTO processed_events (projection_name, tenant_id, event_id, processed_at)
VALUES ($1, $2, $3, clock_timestamp())
ON CONFLICT (projection_name, tenant_id, event_id) DO NOTHING
`

type MarkProcessedEventParams struct {
	ProjectionName string
	TenantID       string
	EventID        uuid.UUID
}

// Records that the inner handler processed this event successfully.
// Idempotent: a duplicate primary-key insert silently succeeds (this
// protects against the race where two replicas process the same event
// before the projection lock is acquired).
func (q *Queries) MarkProcessedEvent(ctx context.Context, arg MarkProcessedEventParams) error {
	_, err := q.db.Exec(ctx, markProcessedEvent, arg.ProjectionName, arg.TenantID, arg.EventID)
	return err
}
