// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projection_checkpoint.sql

package db

import (
	"context"
)

const getProjectionStatus = `-- name: GetProjectionStatus :one
SELECT name, tenant_id, cursor, updated_at
FROM projection_checkpoint
WHERE name      = $1
  AND tenant_id = $2
`

type GetProjectionStatusParams struct {
	Name     string
	TenantID string
}

// Single-projector status row (for the admin Status method).
func (q *Queries) GetProjectionStatus(ctx context.Context, arg GetProjectionStatusParams) (ProjectionCheckpoint, error) {
	row := q.db.QueryRow(ctx, getProjectionStatus, arg.Name, arg.TenantID)
	var i ProjectionCheckpoint
	err := row.Scan(
		&i.Name,
		&i.TenantID,
		&i.Cursor,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectionCheckpoints = `-- name: ListProjectionCheckpoints :many
SELECT name, tenant_id, cursor, updated_at
FROM projection_checkpoint
ORDER BY name, tenant_id
`

// Enumerate all known projectors for an ops dashboard.
func (q *Queries) ListProjectionCheckpoints(ctx context.Context) ([]ProjectionCheckpoint, error) {
	rows, err := q.db.Query(ctx, listProjectionCheckpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectionCheckpoint
	for rows.Next() {
		var i ProjectionCheckpoint
		if err := rows.Scan(
			&i.Name,
			&i.TenantID,
			&i.Cursor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadProjectionCheckpoint = `-- name: LoadProjectionCheckpoint :one

SELECT cursor
FROM projection_checkpoint
WHERE name      = $1
  AND tenant_id = $2
`

type LoadProjectionCheckpointParams struct {
	Name     string
	TenantID string
}

// projection_checkpoint queries (ADR 0020 Tier 3, decision 3e).
// Returns the cursor for a projector. NULL row → 0 (never run).
func (q *Queries) LoadProjectionCheckpoint(ctx context.Context, arg LoadProjectionCheckpointParams) (int64, error) {
	row := q.db.QueryRow(ctx, loadProjectionCheckpoint, arg.Name, arg.TenantID)
	var cursor int64
	err := row.Scan(&cursor)
	return cursor, err
}

const resetProjectionCheckpoint = `-- name: ResetProjectionCheckpoint :exec
INSERT INTO projection_checkpoint (name, tenant_id, cursor, updated_at)
VALUES ($1, $2, 0, clock_timestamp())
ON CONFLICT (name, tenant_id) DO UPDATE SET
    cursor     = 0,
    updated_at = clock_timestamp()
`

type ResetProjectionCheckpointParams struct {
	Name     string
	TenantID string
}

// Operator action: set cursor to 0 (or remove the row, equivalent).
// Used as step (3) of the truncate-and-replay rebuild workflow.
func (q *Queries) ResetProjectionCheckpoint(ctx context.Context, arg ResetProjectionCheckpointParams) error {
	_, err := q.db.Exec(ctx, resetProjectionCheckpoint, arg.Name, arg.TenantID)
	return err
}

const saveProjectionCheckpoint = `-- name: SaveProjectionCheckpoint :exec
INSERT INTO projection_checkpoint (name, tenant_id, cursor, updated_at)
VALUES ($1, $2, $3, clock_timestamp())
ON CONFLICT (name, tenant_id) DO UPDATE SET
    cursor     = EXCLUDED.cursor,
    updated_at = EXCLUDED.updated_at
`

type SaveProjectionCheckpointParams struct {
	Name     string
	TenantID string
	Cursor   int64
}

// Upsert the cursor. Called after each batch (or each successful
// partial-batch, per the fail-stop-with-last-success rule).
func (q *Queries) SaveProjectionCheckpoint(ctx context.Context, arg SaveProjectionCheckpointParams) error {
	_, err := q.db.Exec(ctx, saveProjectionCheckpoint, arg.Name, arg.TenantID, arg.Cursor)
	return err
}

const setProjectionCheckpoint = `-- name: SetProjectionCheckpoint :exec
INSERT INTO projection_checkpoint (name, tenant_id, cursor, updated_at)
VALUES ($1, $2, $3, clock_timestamp())
ON CONFLICT (name, tenant_id) DO UPDATE SET
    cursor     = $3,
    updated_at = clock_timestamp()
`

type SetProjectionCheckpointParams struct {
	Name     string
	TenantID string
	Cursor   int64
}

// Operator action: set cursor to a specific position (for partial
// replay from a known-good point).
func (q *Queries) SetProjectionCheckpoint(ctx context.Context, arg SetProjectionCheckpointParams) error {
	_, err := q.db.Exec(ctx, setProjectionCheckpoint, arg.Name, arg.TenantID, arg.Cursor)
	return err
}
