// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projection_dlq.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const abandonAllProjectionDLQ = `-- name: AbandonAllProjectionDLQ :execrows
DELETE FROM projection_dlq
WHERE projection_name = $1
  AND tenant_id       = $2
`

type AbandonAllProjectionDLQParams struct {
	ProjectionName string
	TenantID       string
}

// Operator action: bulk-delete all DLQ rows for one projection. Used
// after a runbook decision to stop trying to reprocess. The events
// themselves remain in the events table; only the DLQ markers go.
func (q *Queries) AbandonAllProjectionDLQ(ctx context.Context, arg AbandonAllProjectionDLQParams) (int64, error) {
	result, err := q.db.Exec(ctx, abandonAllProjectionDLQ, arg.ProjectionName, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countProjectionDLQ = `-- name: CountProjectionDLQ :one
SELECT COUNT(*)::bigint
FROM projection_dlq
WHERE projection_name = $1
  AND tenant_id       = $2
`

type CountProjectionDLQParams struct {
	ProjectionName string
	TenantID       string
}

func (q *Queries) CountProjectionDLQ(ctx context.Context, arg CountProjectionDLQParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectionDLQ, arg.ProjectionName, arg.TenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteProjectionDLQ = `-- name: DeleteProjectionDLQ :exec
DELETE FROM projection_dlq
WHERE projection_name = $1
  AND tenant_id       = $2
  AND global_position = $3
`

type DeleteProjectionDLQParams struct {
	ProjectionName string
	TenantID       string
	GlobalPosition int64
}

// Operator action: remove a DLQ row (after Replay via ResetTo, or
// after Abandon).
func (q *Queries) DeleteProjectionDLQ(ctx context.Context, arg DeleteProjectionDLQParams) error {
	_, err := q.db.Exec(ctx, deleteProjectionDLQ, arg.ProjectionName, arg.TenantID, arg.GlobalPosition)
	return err
}

const insertProjectionDLQ = `-- name: InsertProjectionDLQ :exec

INSERT INTO projection_dlq (
    projection_name, tenant_id, global_position, event_id, type_url, last_error, enqueued_at
) VALUES (
    $1, $2, $3, $4, $5, $6, clock_timestamp()
)
ON CONFLICT (projection_name, tenant_id, global_position) DO UPDATE SET
    last_error  = EXCLUDED.last_error,
    enqueued_at = EXCLUDED.enqueued_at
`

type InsertProjectionDLQParams struct {
	ProjectionName string
	TenantID       string
	GlobalPosition int64
	EventID        uuid.UUID
	TypeUrl        string
	LastError      string
}

// projection_dlq queries (ADR 0020 deferred — DLQ-skip mode).
// Capture one event that failed under DLQOnFailure. Idempotent: same
// (projection, tenant, global_position) overwrites the existing row
// (handler error message is the most useful version).
func (q *Queries) InsertProjectionDLQ(ctx context.Context, arg InsertProjectionDLQParams) error {
	_, err := q.db.Exec(ctx, insertProjectionDLQ,
		arg.ProjectionName,
		arg.TenantID,
		arg.GlobalPosition,
		arg.EventID,
		arg.TypeUrl,
		arg.LastError,
	)
	return err
}

const listProjectionDLQ = `-- name: ListProjectionDLQ :many
SELECT projection_name, tenant_id, global_position, event_id, type_url, last_error, enqueued_at
FROM projection_dlq
WHERE projection_name = $1
  AND tenant_id       = $2
  AND global_position > $3
ORDER BY global_position
LIMIT $4
`

type ListProjectionDLQParams struct {
	ProjectionName string
	TenantID       string
	AfterPosition  int64
	MaxRows        int32
}

// Paginated listing for an admin dashboard. afterPosition = 0 starts
// from the beginning.
func (q *Queries) ListProjectionDLQ(ctx context.Context, arg ListProjectionDLQParams) ([]ProjectionDlq, error) {
	rows, err := q.db.Query(ctx, listProjectionDLQ,
		arg.ProjectionName,
		arg.TenantID,
		arg.AfterPosition,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectionDlq
	for rows.Next() {
		var i ProjectionDlq
		if err := rows.Scan(
			&i.ProjectionName,
			&i.TenantID,
			&i.GlobalPosition,
			&i.EventID,
			&i.TypeUrl,
			&i.LastError,
			&i.EnqueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
