// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Append-path queries. Used inside a single transaction in the
	// following sequence (see ADR 0009):
	//
	//   1. AdvisoryLock          (serializes all writers store-wide)
	//   2. For each constraint:  ClaimUnique  (in constraint.sql)
	//   3. For each event:       InsertEvent  (allocates global_position)
	//   4. For each event:       InsertOutbox (durable publish backstop)
	//   5. COMMIT
	//
	// Optimistic concurrency is enforced by the events PRIMARY KEY
	// (tenant_id, stream_id, version) — a stale read produces a
	// unique-violation that the adapter translates to ErrConflict.
	// Acquire the store-wide append lock. Auto-releases on commit/rollback.
	// The constant is the framework's reserved lock key for this table.
	AdvisoryLock(ctx context.Context, lockKey int64) error
	// First-class uniqueness primitives (ADR 0010).
	//
	// A claim is inserted in the same transaction as the events that produce
	// it. The UNIQUE(tenant_id, scope, value) PK enforces transactional
	// uniqueness — a conflict fails the entire append, which the adapter
	// translates to ErrConstraintViolated.
	//
	// Cross-tenant uniqueness uses tenant_id = '__global__' explicitly; the
	// framework refuses to set this implicitly.
	ClaimUnique(ctx context.Context, arg ClaimUniqueParams) error
	// Retention pruning. Deletes rows that have been published longer than
	// @older_than. Runs in the same scheduled wake-up as the publish drain.
	CleanupPublished(ctx context.Context, arg CleanupPublishedParams) error
	// Returns the current version of a stream, or 0 if the stream is empty.
	// Used for optimistic-concurrency hints; not for primary correctness
	// (that comes from the PK conflict at append time).
	CurrentStreamVersion(ctx context.Context, arg CurrentStreamVersionParams) (int64, error)
	// Operational tool: force a full-replay on next read.
	DeleteSnapshot(ctx context.Context, arg DeleteSnapshotParams) error
	// Crypto-shred a subject. Sets the wrapped DEK to empty bytes and marks
	// the shred timestamp. The row is retained for compliance audit.
	ForgetSubject(ctx context.Context, arg ForgetSubjectParams) error
	// Single-event lookup, typically for idempotency or dedup audits.
	GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error)
	// Snapshot queries (ADR 0011).
	//
	// Lazy snapshots: written on read after N events since the last
	// snapshot. Latest wins per stream.
	GetSnapshot(ctx context.Context, arg GetSnapshotParams) (Snapshot, error)
	// Crypto-shredding subject-key queries (ADR 0010).
	//
	// DEKs are stored wrapped by the tenant's KEK (held in the configured
	// KMS adapter). Shredding zeroes the wrapped DEK and tombstones the
	// row for compliance audit.
	GetSubjectKey(ctx context.Context, arg GetSubjectKeyParams) (SubjectKey, error)
	GetUniqueClaim(ctx context.Context, arg GetUniqueClaimParams) (UniqueClaim, error)
	// Insert one event, allocating its global_position from the sequence
	// under the advisory lock. Returns the assigned position and the DB
	// commit timestamp so callers can echo them back on the envelope.
	InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error)
	// Insert the outbox row for an event. The drain process polls
	// outbox_pending_idx and hands rows to the configured EventPublisher.
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	// Audit query: enumerate subjects that have been crypto-shredded for a
	// tenant. Useful for compliance reports.
	ListShreddedSubjects(ctx context.Context, arg ListShreddedSubjectsParams) ([]ListShreddedSubjectsRow, error)
	// Increment attempts and record the error. The next drain run retries;
	// exponential backoff is the publisher's concern, not the outbox's.
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error
	// Outbox queries (ADR 0014).
	//
	// The drain process wakes the database on a schedule, pulls pending
	// rows in global_position order, fetches the envelope+payload via a
	// JOIN to events, hands off to the EventPublisher, then marks each row
	// published. The same wake-up also runs the cleanup pass.
	// Tenant-scoped pending rows. Hot path for per-tenant publishers.
	PendingOutboxRows(ctx context.Context, arg PendingOutboxRowsParams) ([]Outbox, error)
	// Cross-tenant pending rows. Used by the shared scheduled drain that
	// handles all tenants in one wake-up.
	PendingOutboxRowsAllTenants(ctx context.Context, maxRows int32) ([]Outbox, error)
	// Drain hot path: pending rows joined to their envelope+payload, ready
	// to hand to the publisher.
	PendingOutboxWithEnvelope(ctx context.Context, maxRows int32) ([]PendingOutboxWithEnvelopeRow, error)
	// Cross-tenant catch-up read. Used by gap-fill in subscribers and by
	// admin-scope projections (billing, compliance).
	ReadAllFromPosition(ctx context.Context, arg ReadAllFromPositionParams) ([]Event, error)
	// Tenant-scoped catch-up read. Used by per-tenant projection rebuilds.
	ReadAllFromPositionTenant(ctx context.Context, arg ReadAllFromPositionTenantParams) ([]Event, error)
	// Read-path queries.
	//
	// Three modes:
	//   * Per-stream replay  (aggregate command path, snapshot rebuild)
	//   * Store-wide replay  (projection rebuild, gap-fill from bus consumers)
	//   * Per-tenant replay  (projection rebuild scoped to one tenant)
	// Full per-stream replay from version 1.
	ReadStream(ctx context.Context, arg ReadStreamParams) ([]Event, error)
	// Per-stream replay starting after a known version (typical when a
	// snapshot exists at @after_version).
	ReadStreamFromVersion(ctx context.Context, arg ReadStreamFromVersionParams) ([]Event, error)
	ReleaseUnique(ctx context.Context, arg ReleaseUniqueParams) error
	// Write or replace the snapshot for a stream. state_schema_version is
	// the decider state's shape version; mismatches at read time are
	// silently discarded with full-replay fallback.
	UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) error
	// Used at first encryption for a subject (create the DEK) and during
	// KEK rotation (re-wrap the existing DEK under the new KEK version).
	UpsertSubjectKey(ctx context.Context, arg UpsertSubjectKeyParams) error
}

var _ Querier = (*Queries)(nil)
