// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	// Operator action: bulk-delete all DLQ rows for one projection. Used
	// after a runbook decision to stop trying to reprocess. The events
	// themselves remain in the events table; only the DLQ markers go.
	AbandonAllProjectionDLQ(ctx context.Context, arg AbandonAllProjectionDLQParams) (int64, error)
	// Mark a DLQ'd row as published (set published_at = now) without
	// actually publishing. Use when an event is genuinely garbage. The
	// event itself stays in the events table (ADR 0005); only the
	// outbox row is closed.
	AbandonDLQ(ctx context.Context, arg AbandonDLQParams) error
	// Append-path queries. Used inside a single transaction in the
	// following sequence (see ADR 0009):
	//
	//   1. AdvisoryLock          (serializes all writers store-wide)
	//   2. For each constraint:  ClaimUnique  (in constraint.sql)
	//   3. For each event:       InsertEvent  (allocates global_position)
	//   4. For each event:       InsertOutbox (durable publish backstop)
	//   5. COMMIT
	//
	// Optimistic concurrency is enforced by the events PRIMARY KEY
	// (tenant_id, stream_id, version) — a stale read produces a
	// unique-violation that the adapter translates to ErrConflict.
	// Acquire the store-wide append lock. Auto-releases on commit/rollback.
	// The constant is the framework's reserved lock key for this table.
	AdvisoryLock(ctx context.Context, lockKey int64) error
	// First-class uniqueness primitives (ADR 0010).
	//
	// A claim is inserted in the same transaction as the events that produce
	// it. The UNIQUE(tenant_id, scope, value) PK enforces transactional
	// uniqueness — a conflict fails the entire append, which the adapter
	// translates to ErrConstraintViolated.
	//
	// Cross-tenant uniqueness uses tenant_id = '__global__' explicitly; the
	// framework refuses to set this implicitly.
	ClaimUnique(ctx context.Context, arg ClaimUniqueParams) error
	// Retention pruning. Deletes processed_events rows older than
	// @older_than. Returns the number of rows deleted. Operators run this
	// periodically since the table grows monotonically with event count.
	CleanupProcessedEvents(ctx context.Context, arg CleanupProcessedEventsParams) (int64, error)
	// Retention pruning. Deletes rows that have been published longer
	// than @older_than. Runs in the same scheduled wake-up as the
	// publish drain.
	CleanupPublished(ctx context.Context, arg CleanupPublishedParams) error
	// Count of rows in DLQ state. Gauge metric.
	CountDLQ(ctx context.Context, arg CountDLQParams) (int64, error)
	// Rows that have failed at least once but not yet hit DLQ.
	// Worth watching but not alarming.
	CountFailing(ctx context.Context, arg CountFailingParams) (int64, error)
	// Total pending (unpublished) rows. Gauge metric.
	CountPending(ctx context.Context, tenantID string) (int64, error)
	CountProjectionDLQ(ctx context.Context, arg CountProjectionDLQParams) (int64, error)
	// How many streams is the subscriber behind on, and what's the largest
	// gap? Used for operator dashboards / alerting per ADR 0024 § 6.
	CountStateStreamLag(ctx context.Context, arg CountStateStreamLagParams) (CountStateStreamLagRow, error)
	// Returns the current version of a stream, or 0 if the stream is empty.
	// Used for optimistic-concurrency hints; not for primary correctness
	// (that comes from the PK conflict at append time).
	CurrentStreamVersion(ctx context.Context, arg CurrentStreamVersionParams) (int64, error)
	// Operator action: remove a DLQ row (after Replay via ResetTo, or
	// after Abandon).
	DeleteProjectionDLQ(ctx context.Context, arg DeleteProjectionDLQParams) error
	// Wipe state_cache rows for a given type before a rebuild. Returns the
	// number of rows deleted.
	DeleteStateCacheForType(ctx context.Context, arg DeleteStateCacheForTypeParams) (int64, error)
	// Cross-tenant variant for full rebuild.
	DeleteStateCacheForTypeAllTenants(ctx context.Context, typeUrl string) (int64, error)
	// Crypto-shred a subject. Sets the wrapped DEK to empty bytes and marks
	// the shred timestamp. The row is retained for compliance audit.
	ForgetSubject(ctx context.Context, arg ForgetSubjectParams) error
	// Single-event lookup, typically for idempotency or dedup audits.
	GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error)
	// Single-projector status row (for the admin Status method).
	GetProjectionStatus(ctx context.Context, arg GetProjectionStatusParams) (ProjectionCheckpoint, error)
	// Tier 1 point lookup. Returns nothing if the stream has no cached
	// state (either never written or the aggregate is not opted in).
	GetState(ctx context.Context, arg GetStateParams) (GetStateRow, error)
	// Crypto-shredding subject-key queries (ADR 0010).
	//
	// DEKs are stored wrapped by the tenant's KEK (held in the configured
	// KMS adapter). Shredding zeroes the wrapped DEK and tombstones the
	// row for compliance audit.
	GetSubjectKey(ctx context.Context, arg GetSubjectKeyParams) (SubjectKey, error)
	GetUniqueClaim(ctx context.Context, arg GetUniqueClaimParams) (UniqueClaim, error)
	// processed_events queries (ADR 0020 — WithDedup escape hatch).
	// Returns true if (projection_name, tenant_id, event_id) is already
	// recorded. The wrapper checks this before invoking the inner handler.
	HasProcessedEvent(ctx context.Context, arg HasProcessedEventParams) (bool, error)
	// Insert one event, allocating its global_position from the sequence
	// under the advisory lock. Returns the assigned position and the DB
	// commit timestamp so callers can echo them back on the envelope.
	InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error)
	// Insert the outbox row for an event. The drain process polls
	// outbox_pending_idx and hands rows to the configured EventPublisher.
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	// projection_dlq queries (ADR 0020 deferred — DLQ-skip mode).
	// Capture one event that failed under DLQOnFailure. Idempotent: same
	// (projection, tenant, global_position) overwrites the existing row
	// (handler error message is the most useful version).
	InsertProjectionDLQ(ctx context.Context, arg InsertProjectionDLQParams) error
	// ===========================================================================
	// Admin / dashboard queries
	// ===========================================================================
	// Paginated listing of rows in DLQ state (attempts >= @max_attempts
	// AND not yet published). Pass the global_position of the last row
	// in the previous page as @after_position to fetch the next page;
	// start with @after_position = 0.
	ListDLQ(ctx context.Context, arg ListDLQParams) ([]ListDLQRow, error)
	// Enumerate all known projectors for an ops dashboard.
	ListProjectionCheckpoints(ctx context.Context) ([]ProjectionCheckpoint, error)
	// Paginated listing for an admin dashboard. afterPosition = 0 starts
	// from the beginning.
	ListProjectionDLQ(ctx context.Context, arg ListProjectionDLQParams) ([]ProjectionDlq, error)
	// Audit query: enumerate subjects that have been crypto-shredded for a
	// tenant. Useful for compliance reports.
	ListShreddedSubjects(ctx context.Context, arg ListShreddedSubjectsParams) ([]ListShreddedSubjectsRow, error)
	// Returns subject_keys rows wrapped under an older KEK version. Used
	// by shred.RewrapDEKs to migrate historical DEKs after a KEK rotation
	// (ADR 0010). Shredded rows are skipped — their DEKs are deliberately
	// inaccessible.
	ListStaleSubjectKeys(ctx context.Context, arg ListStaleSubjectKeysParams) ([]SubjectKey, error)
	// Returns the distinct subscriber names present in the table — used
	// by Admin.List.
	ListStateStreamSubscribers(ctx context.Context) ([]string, error)
	// Paged listing of cached states for a given type_url. Pass the
	// stream_id of the last row in the previous page as @after_stream_id
	// to fetch the next page; start with @after_stream_id = ''.
	ListStates(ctx context.Context, arg ListStatesParams) ([]ListStatesRow, error)
	// Cross-tenant variant. Admin/operator-scope use only.
	ListStatesAll(ctx context.Context, arg ListStatesAllParams) ([]ListStatesAllRow, error)
	// state_stream queries (ADR 0024).
	// Drain hot path: returns up to @max_rows streams where the named
	// subscriber's position is behind state_cache.version. The state
	// payload comes from state_cache (no duplication of state bytes).
	// Tenant filter: pass @tenant_id = '' for cross-tenant drain.
	ListStreamsBehind(ctx context.Context, arg ListStreamsBehindParams) ([]ListStreamsBehindRow, error)
	// projection_checkpoint queries (ADR 0020 Tier 3, decision 3e).
	// Returns the cursor for a projector. NULL row → 0 (never run).
	LoadProjectionCheckpoint(ctx context.Context, arg LoadProjectionCheckpointParams) (int64, error)
	// Increment attempts, record the last error, and set the next
	// retry-eligible time. The Drain computes next_attempt_at via its
	// backoff function and passes it in.
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error
	// Records that the inner handler processed this event successfully.
	// Idempotent: a duplicate primary-key insert silently succeeds (this
	// protects against the race where two replicas process the same event
	// before the projection lock is acquired).
	MarkProcessedEvent(ctx context.Context, arg MarkProcessedEventParams) error
	// Returns the earliest enqueued_at among pending rows, or NULL if
	// the pending set is empty. Compute lag = now() - this in app code.
	OldestPendingEnqueuedAt(ctx context.Context, tenantID string) (time.Time, error)
	// Outbox queries (ADR 0014).
	//
	// The drain process wakes the database on a schedule, pulls pending
	// rows in global_position order, fetches the envelope+payload via a
	// JOIN to events, hands off to the EventPublisher, then marks each row
	// published. The same wake-up also runs the cleanup pass.
	// Tenant-scoped pending rows. Hot path for per-tenant publishers.
	PendingOutboxRows(ctx context.Context, arg PendingOutboxRowsParams) ([]Outbox, error)
	// Cross-tenant pending rows. Used by the shared scheduled drain that
	// handles all tenants in one wake-up.
	PendingOutboxRowsAllTenants(ctx context.Context, maxRows int32) ([]Outbox, error)
	// Drain hot path: pending rows joined to their envelope+payload,
	// filtered by retry-readiness, max-attempts (DLQ threshold), and the
	// per-stream "head" rule. The head rule (NOT EXISTS subquery) blocks
	// any row whose stream has a lower-version unpublished, not-yet-DLQ'd
	// row — preserving per-stream order even across leader handoffs when
	// backoff puts the head in cooldown. DLQ'd rows (attempts >=
	// @max_attempts) don't block, so the AutoResumeAfterDLQ=true path can
	// step past them. The DLQ-quarantines-stream semantic
	// (AutoResumeAfterDLQ=false) is layered on by the drain via
	// QuarantinedStreams, not by this query.
	PendingOutboxWithEnvelope(ctx context.Context, arg PendingOutboxWithEnvelopeParams) ([]PendingOutboxWithEnvelopeRow, error)
	// Returns the distinct (tenant_id, stream_id) pairs that have at
	// least one outbox row in DLQ state (attempts >= max_attempts AND
	// published_at IS NULL). The drain uses this to skip ALL rows of a
	// stream once any row enters DLQ, preserving per-stream order
	// (no gap delivery without operator intervention).
	QuarantinedStreams(ctx context.Context, arg QuarantinedStreamsParams) ([]QuarantinedStreamsRow, error)
	QuarantinedStreamsAllTenants(ctx context.Context, maxAttempts int32) ([]QuarantinedStreamsAllTenantsRow, error)
	// Cross-tenant catch-up read. Used by gap-fill in subscribers and by
	// admin-scope projections (billing, compliance).
	ReadAllFromPosition(ctx context.Context, arg ReadAllFromPositionParams) ([]Event, error)
	// Tenant-scoped catch-up read. Used by per-tenant projection rebuilds.
	ReadAllFromPositionTenant(ctx context.Context, arg ReadAllFromPositionTenantParams) ([]Event, error)
	// Read-path queries.
	//
	// Three modes:
	//   * Per-stream replay  (aggregate command path, snapshot rebuild)
	//   * Store-wide replay  (projection rebuild, gap-fill from bus consumers)
	//   * Per-tenant replay  (projection rebuild scoped to one tenant)
	// Full per-stream replay from version 1.
	ReadStream(ctx context.Context, arg ReadStreamParams) ([]Event, error)
	// Per-stream replay starting after a known version (typical when a
	// snapshot exists at @after_version).
	ReadStreamFromVersion(ctx context.Context, arg ReadStreamFromVersionParams) ([]Event, error)
	ReleaseUnique(ctx context.Context, arg ReleaseUniqueParams) error
	// Bulk-replay every DLQ'd row for a tenant. Useful after a
	// publisher outage recovery. Returns the number of rows reset.
	ReplayAllDLQ(ctx context.Context, arg ReplayAllDLQParams) (int64, error)
	// Reset a single row's attempts/backoff so the next drain run picks
	// it up. Used by operators after fixing root cause.
	ReplayDLQ(ctx context.Context, arg ReplayDLQParams) error
	// Operator action: set cursor to 0 (or remove the row, equivalent).
	// Used as step (3) of the truncate-and-replay rebuild workflow.
	ResetProjectionCheckpoint(ctx context.Context, arg ResetProjectionCheckpointParams) error
	// Operator action: delete every position for one subscriber. Next
	// drain will full-backfill (current state of every stream). Returns
	// the count of rows deleted.
	ResetStateStreamSubscriber(ctx context.Context, arg ResetStateStreamSubscriberParams) (int64, error)
	// Single-stream rewind: delete the position row for one stream so the
	// drain redelivers the current state on its next pass. Used after the
	// crypto-shred propagation runbook (ADR 0024 § Crypto-shred).
	ResetStateStreamSubscriberForStream(ctx context.Context, arg ResetStateStreamSubscriberForStreamParams) error
	// Upsert the cursor. Called after each batch (or each successful
	// partial-batch, per the fail-stop-with-last-success rule).
	SaveProjectionCheckpoint(ctx context.Context, arg SaveProjectionCheckpointParams) error
	// Operator action: set cursor to a specific position (for partial
	// replay from a known-good point).
	SetProjectionCheckpoint(ctx context.Context, arg SetProjectionCheckpointParams) error
	// state_cache queries (ADR 0020 Tier 1).
	//
	// One row per (tenant_id, stream_id). Written transactionally with
	// events via UpsertStateCache (called from Append). Read via GetState /
	// ListStates / ListStatesAll.
	// Atomic upsert: insert on first append, update on subsequent. Called
	// from within the events-append transaction.
	UpsertStateCache(ctx context.Context, arg UpsertStateCacheParams) error
	// Advance the subscriber's position for one stream after a successful
	// delivery. Last-delivered-version is monotonically non-decreasing for
	// a given (name, tenant_id, stream_id).
	UpsertStateStreamPosition(ctx context.Context, arg UpsertStateStreamPositionParams) error
	// Used at first encryption for a subject (create the DEK) and during
	// KEK rotation (re-wrap the existing DEK under the new KEK version).
	UpsertSubjectKey(ctx context.Context, arg UpsertSubjectKeyParams) error
}

var _ Querier = (*Queries)(nil)
