// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const currentStreamVersion = `-- name: CurrentStreamVersion :one
SELECT COALESCE(MAX(version), 0)::bigint AS current_version
FROM events
WHERE tenant_id = $1
  AND stream_id = $2
`

type CurrentStreamVersionParams struct {
	TenantID string
	StreamID string
}

// Returns the current version of a stream, or 0 if the stream is empty.
// Used for optimistic-concurrency hints; not for primary correctness
// (that comes from the PK conflict at append time).
func (q *Queries) CurrentStreamVersion(ctx context.Context, arg CurrentStreamVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, currentStreamVersion, arg.TenantID, arg.StreamID)
	var current_version int64
	err := row.Scan(&current_version)
	return current_version, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT event_id, tenant_id, stream_id, version, global_position, type_url, schema_version, occurred_at, recorded_at, correlation_id, causation_id, command_id, actor, actor_principal, payload, payload_json, encryption_key_refs
FROM events
WHERE tenant_id = $1
  AND event_id = $2
`

type GetEventByIDParams struct {
	TenantID string
	EventID  uuid.UUID
}

// Single-event lookup, typically for idempotency or dedup audits.
func (q *Queries) GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, arg.TenantID, arg.EventID)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.TenantID,
		&i.StreamID,
		&i.Version,
		&i.GlobalPosition,
		&i.TypeUrl,
		&i.SchemaVersion,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.CorrelationID,
		&i.CausationID,
		&i.CommandID,
		&i.Actor,
		&i.ActorPrincipal,
		&i.Payload,
		&i.PayloadJson,
		&i.EncryptionKeyRefs,
	)
	return i, err
}

const readAllFromPosition = `-- name: ReadAllFromPosition :many
SELECT event_id, tenant_id, stream_id, version, global_position, type_url, schema_version, occurred_at, recorded_at, correlation_id, causation_id, command_id, actor, actor_principal, payload, payload_json, encryption_key_refs
FROM events
WHERE global_position > $1
ORDER BY global_position
LIMIT $2
`

type ReadAllFromPositionParams struct {
	AfterPosition int64
	MaxRows       int32
}

// Cross-tenant catch-up read. Used by gap-fill in subscribers and by
// admin-scope projections (billing, compliance).
func (q *Queries) ReadAllFromPosition(ctx context.Context, arg ReadAllFromPositionParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, readAllFromPosition, arg.AfterPosition, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.StreamID,
			&i.Version,
			&i.GlobalPosition,
			&i.TypeUrl,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.Actor,
			&i.ActorPrincipal,
			&i.Payload,
			&i.PayloadJson,
			&i.EncryptionKeyRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readAllFromPositionTenant = `-- name: ReadAllFromPositionTenant :many
SELECT event_id, tenant_id, stream_id, version, global_position, type_url, schema_version, occurred_at, recorded_at, correlation_id, causation_id, command_id, actor, actor_principal, payload, payload_json, encryption_key_refs
FROM events
WHERE tenant_id = $1
  AND global_position > $2
ORDER BY global_position
LIMIT $3
`

type ReadAllFromPositionTenantParams struct {
	TenantID      string
	AfterPosition int64
	MaxRows       int32
}

// Tenant-scoped catch-up read. Used by per-tenant projection rebuilds.
func (q *Queries) ReadAllFromPositionTenant(ctx context.Context, arg ReadAllFromPositionTenantParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, readAllFromPositionTenant, arg.TenantID, arg.AfterPosition, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.StreamID,
			&i.Version,
			&i.GlobalPosition,
			&i.TypeUrl,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.Actor,
			&i.ActorPrincipal,
			&i.Payload,
			&i.PayloadJson,
			&i.EncryptionKeyRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readStream = `-- name: ReadStream :many

SELECT event_id, tenant_id, stream_id, version, global_position, type_url, schema_version, occurred_at, recorded_at, correlation_id, causation_id, command_id, actor, actor_principal, payload, payload_json, encryption_key_refs
FROM events
WHERE tenant_id = $1
  AND stream_id = $2
ORDER BY version
`

type ReadStreamParams struct {
	TenantID string
	StreamID string
}

// Read-path queries.
//
// Three modes:
//   - Per-stream replay  (aggregate command path, snapshot rebuild)
//   - Store-wide replay  (projection rebuild, gap-fill from bus consumers)
//   - Per-tenant replay  (projection rebuild scoped to one tenant)
//
// Full per-stream replay from version 1.
func (q *Queries) ReadStream(ctx context.Context, arg ReadStreamParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, readStream, arg.TenantID, arg.StreamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.StreamID,
			&i.Version,
			&i.GlobalPosition,
			&i.TypeUrl,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.Actor,
			&i.ActorPrincipal,
			&i.Payload,
			&i.PayloadJson,
			&i.EncryptionKeyRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readStreamFromVersion = `-- name: ReadStreamFromVersion :many
SELECT event_id, tenant_id, stream_id, version, global_position, type_url, schema_version, occurred_at, recorded_at, correlation_id, causation_id, command_id, actor, actor_principal, payload, payload_json, encryption_key_refs
FROM events
WHERE tenant_id = $1
  AND stream_id = $2
  AND version > $3
ORDER BY version
`

type ReadStreamFromVersionParams struct {
	TenantID     string
	StreamID     string
	AfterVersion int64
}

// Per-stream replay starting after a known version (typical when a
// snapshot exists at @after_version).
func (q *Queries) ReadStreamFromVersion(ctx context.Context, arg ReadStreamFromVersionParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, readStreamFromVersion, arg.TenantID, arg.StreamID, arg.AfterVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.StreamID,
			&i.Version,
			&i.GlobalPosition,
			&i.TypeUrl,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.CommandID,
			&i.Actor,
			&i.ActorPrincipal,
			&i.Payload,
			&i.PayloadJson,
			&i.EncryptionKeyRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
