// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shred.sql

package db

import (
	"context"
	"time"
)

const forgetSubject = `-- name: ForgetSubject :exec
UPDATE subject_keys
SET dek_wrapped = ''::bytea,
    shredded_at = clock_timestamp()
WHERE tenant_id = $1
  AND subject = $2
`

type ForgetSubjectParams struct {
	TenantID string
	Subject  string
}

// Crypto-shred a subject. Sets the wrapped DEK to empty bytes and marks
// the shred timestamp. The row is retained for compliance audit.
func (q *Queries) ForgetSubject(ctx context.Context, arg ForgetSubjectParams) error {
	_, err := q.db.Exec(ctx, forgetSubject, arg.TenantID, arg.Subject)
	return err
}

const getSubjectKey = `-- name: GetSubjectKey :one

SELECT tenant_id, subject, dek_wrapped, kek_version, created_at, shredded_at
FROM subject_keys
WHERE tenant_id = $1
  AND subject = $2
`

type GetSubjectKeyParams struct {
	TenantID string
	Subject  string
}

// Crypto-shredding subject-key queries (ADR 0010).
//
// DEKs are stored wrapped by the tenant's KEK (held in the configured
// KMS adapter). Shredding zeroes the wrapped DEK and tombstones the
// row for compliance audit.
func (q *Queries) GetSubjectKey(ctx context.Context, arg GetSubjectKeyParams) (SubjectKey, error) {
	row := q.db.QueryRow(ctx, getSubjectKey, arg.TenantID, arg.Subject)
	var i SubjectKey
	err := row.Scan(
		&i.TenantID,
		&i.Subject,
		&i.DekWrapped,
		&i.KekVersion,
		&i.CreatedAt,
		&i.ShreddedAt,
	)
	return i, err
}

const listShreddedSubjects = `-- name: ListShreddedSubjects :many
SELECT subject, shredded_at
FROM subject_keys
WHERE tenant_id = $1
  AND shredded_at IS NOT NULL
ORDER BY shredded_at DESC
LIMIT $2
`

type ListShreddedSubjectsParams struct {
	TenantID string
	MaxRows  int32
}

type ListShreddedSubjectsRow struct {
	Subject    string
	ShreddedAt *time.Time
}

// Audit query: enumerate subjects that have been crypto-shredded for a
// tenant. Useful for compliance reports.
func (q *Queries) ListShreddedSubjects(ctx context.Context, arg ListShreddedSubjectsParams) ([]ListShreddedSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listShreddedSubjects, arg.TenantID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShreddedSubjectsRow
	for rows.Next() {
		var i ListShreddedSubjectsRow
		if err := rows.Scan(&i.Subject, &i.ShreddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleSubjectKeys = `-- name: ListStaleSubjectKeys :many
SELECT tenant_id, subject, dek_wrapped, kek_version, created_at, shredded_at
FROM subject_keys
WHERE tenant_id    = $1
  AND kek_version  < $2
  AND shredded_at IS NULL
ORDER BY subject
LIMIT $3
`

type ListStaleSubjectKeysParams struct {
	TenantID          string
	CurrentKekVersion int32
	MaxRows           int32
}

// Returns subject_keys rows wrapped under an older KEK version. Used
// by shred.RewrapDEKs to migrate historical DEKs after a KEK rotation
// (ADR 0010). Shredded rows are skipped — their DEKs are deliberately
// inaccessible.
func (q *Queries) ListStaleSubjectKeys(ctx context.Context, arg ListStaleSubjectKeysParams) ([]SubjectKey, error) {
	rows, err := q.db.Query(ctx, listStaleSubjectKeys, arg.TenantID, arg.CurrentKekVersion, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubjectKey
	for rows.Next() {
		var i SubjectKey
		if err := rows.Scan(
			&i.TenantID,
			&i.Subject,
			&i.DekWrapped,
			&i.KekVersion,
			&i.CreatedAt,
			&i.ShreddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectsCreatedBefore = `-- name: ListSubjectsCreatedBefore :many
SELECT tenant_id, subject, dek_wrapped, kek_version, created_at, shredded_at
FROM subject_keys
WHERE tenant_id   = $1
  AND shredded_at IS NULL
  AND created_at  < $2
ORDER BY subject
LIMIT $3
`

type ListSubjectsCreatedBeforeParams struct {
	TenantID string
	Cutoff   time.Time
	MaxRows  int32
}

// Returns non-shredded subject_keys rows whose DEK was minted before
// the cutoff. Used by shred.RetentionWorker to identify subjects
// eligible for retention shredding. Shredded rows are skipped — their
// DEKs are already destroyed. Pagination by subject keeps the order
// stable across resumed sweeps.
func (q *Queries) ListSubjectsCreatedBefore(ctx context.Context, arg ListSubjectsCreatedBeforeParams) ([]SubjectKey, error) {
	rows, err := q.db.Query(ctx, listSubjectsCreatedBefore, arg.TenantID, arg.Cutoff, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubjectKey
	for rows.Next() {
		var i SubjectKey
		if err := rows.Scan(
			&i.TenantID,
			&i.Subject,
			&i.DekWrapped,
			&i.KekVersion,
			&i.CreatedAt,
			&i.ShreddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubjectKey = `-- name: UpsertSubjectKey :exec
INSERT INTO subject_keys (tenant_id, subject, dek_wrapped, kek_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, subject) DO UPDATE SET
    dek_wrapped = EXCLUDED.dek_wrapped,
    kek_version = EXCLUDED.kek_version
`

type UpsertSubjectKeyParams struct {
	TenantID   string
	Subject    string
	DekWrapped []byte
	KekVersion int32
}

// Used at first encryption for a subject (create the DEK) and during
// KEK rotation (re-wrap the existing DEK under the new KEK version).
func (q *Queries) UpsertSubjectKey(ctx context.Context, arg UpsertSubjectKeyParams) error {
	_, err := q.db.Exec(ctx, upsertSubjectKey,
		arg.TenantID,
		arg.Subject,
		arg.DekWrapped,
		arg.KekVersion,
	)
	return err
}
