// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshot.sql

package db

import (
	"context"
)

const deleteSnapshot = `-- name: DeleteSnapshot :exec
DELETE FROM snapshots
WHERE tenant_id = $1
  AND stream_id = $2
`

type DeleteSnapshotParams struct {
	TenantID string
	StreamID string
}

// Operational tool: force a full-replay on next read.
func (q *Queries) DeleteSnapshot(ctx context.Context, arg DeleteSnapshotParams) error {
	_, err := q.db.Exec(ctx, deleteSnapshot, arg.TenantID, arg.StreamID)
	return err
}

const getSnapshot = `-- name: GetSnapshot :one

SELECT tenant_id, stream_id, version, state_schema_version, state, created_at
FROM snapshots
WHERE tenant_id = $1
  AND stream_id = $2
`

type GetSnapshotParams struct {
	TenantID string
	StreamID string
}

// Snapshot queries (ADR 0011).
//
// Lazy snapshots: written on read after N events since the last
// snapshot. Latest wins per stream.
func (q *Queries) GetSnapshot(ctx context.Context, arg GetSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshot, arg.TenantID, arg.StreamID)
	var i Snapshot
	err := row.Scan(
		&i.TenantID,
		&i.StreamID,
		&i.Version,
		&i.StateSchemaVersion,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSnapshot = `-- name: UpsertSnapshot :exec
INSERT INTO snapshots (tenant_id, stream_id, version, state_schema_version, state)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, stream_id) DO UPDATE SET
    version              = EXCLUDED.version,
    state_schema_version = EXCLUDED.state_schema_version,
    state                = EXCLUDED.state,
    created_at           = clock_timestamp()
`

type UpsertSnapshotParams struct {
	TenantID           string
	StreamID           string
	Version            int64
	StateSchemaVersion int32
	State              []byte
}

// Write or replace the snapshot for a stream. state_schema_version is
// the decider state's shape version; mismatches at read time are
// silently discarded with full-replay fallback.
func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertSnapshot,
		arg.TenantID,
		arg.StreamID,
		arg.Version,
		arg.StateSchemaVersion,
		arg.State,
	)
	return err
}
