// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: state_stream.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const countStateStreamLag = `-- name: CountStateStreamLag :one
SELECT
    COUNT(*)::bigint                          AS streams_behind,
    COALESCE(MAX(sc.version - COALESCE(p.last_delivered_version, 0)), 0)::bigint AS max_lag_versions
FROM state_cache sc
LEFT JOIN state_stream_subscribers p
       ON p.name      = $1
      AND p.tenant_id = sc.tenant_id
      AND p.stream_id = sc.stream_id
WHERE sc.version > COALESCE(p.last_delivered_version, 0)
  AND ($2::text = '' OR sc.tenant_id = $2)
`

type CountStateStreamLagParams struct {
	Name     string
	TenantID string
}

type CountStateStreamLagRow struct {
	StreamsBehind  int64
	MaxLagVersions int64
}

// How many streams is the subscriber behind on, and what's the largest
// gap? Used for operator dashboards / alerting per ADR 0024 § 6.
func (q *Queries) CountStateStreamLag(ctx context.Context, arg CountStateStreamLagParams) (CountStateStreamLagRow, error) {
	row := q.db.QueryRow(ctx, countStateStreamLag, arg.Name, arg.TenantID)
	var i CountStateStreamLagRow
	err := row.Scan(&i.StreamsBehind, &i.MaxLagVersions)
	return i, err
}

const listStateStreamSubscribers = `-- name: ListStateStreamSubscribers :many
SELECT DISTINCT name FROM state_stream_subscribers ORDER BY name
`

// Returns the distinct subscriber names present in the table — used
// by Admin.List.
func (q *Queries) ListStateStreamSubscribers(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listStateStreamSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamsBehind = `-- name: ListStreamsBehind :many

SELECT
    sc.tenant_id,
    sc.stream_id,
    sc.type_url,
    sc.state,
    sc.version,
    sc.state_schema_version,
    sc.updated_at,
    COALESCE(p.last_delivered_version, 0) AS last_delivered_version
FROM state_cache sc
LEFT JOIN state_stream_subscribers p
       ON p.name      = $1
      AND p.tenant_id = sc.tenant_id
      AND p.stream_id = sc.stream_id
WHERE sc.version > COALESCE(p.last_delivered_version, 0)
  AND ($2::text = '' OR sc.tenant_id = $2)
ORDER BY sc.updated_at
LIMIT $3
`

type ListStreamsBehindParams struct {
	Name     string
	TenantID string
	MaxRows  int32
}

type ListStreamsBehindRow struct {
	TenantID             string
	StreamID             string
	TypeUrl              string
	State                json.RawMessage
	Version              int64
	StateSchemaVersion   int32
	UpdatedAt            time.Time
	LastDeliveredVersion int64
}

// state_stream queries (ADR 0024).
// Drain hot path: returns up to @max_rows streams where the named
// subscriber's position is behind state_cache.version. The state
// payload comes from state_cache (no duplication of state bytes).
// Tenant filter: pass @tenant_id = ” for cross-tenant drain.
func (q *Queries) ListStreamsBehind(ctx context.Context, arg ListStreamsBehindParams) ([]ListStreamsBehindRow, error) {
	rows, err := q.db.Query(ctx, listStreamsBehind, arg.Name, arg.TenantID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStreamsBehindRow
	for rows.Next() {
		var i ListStreamsBehindRow
		if err := rows.Scan(
			&i.TenantID,
			&i.StreamID,
			&i.TypeUrl,
			&i.State,
			&i.Version,
			&i.StateSchemaVersion,
			&i.UpdatedAt,
			&i.LastDeliveredVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetStateStreamSubscriber = `-- name: ResetStateStreamSubscriber :execrows
DELETE FROM state_stream_subscribers
WHERE name      = $1
  AND tenant_id = $2
`

type ResetStateStreamSubscriberParams struct {
	Name     string
	TenantID string
}

// Operator action: delete every position for one subscriber. Next
// drain will full-backfill (current state of every stream). Returns
// the count of rows deleted.
func (q *Queries) ResetStateStreamSubscriber(ctx context.Context, arg ResetStateStreamSubscriberParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetStateStreamSubscriber, arg.Name, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetStateStreamSubscriberForStream = `-- name: ResetStateStreamSubscriberForStream :exec
DELETE FROM state_stream_subscribers
WHERE name      = $1
  AND tenant_id = $2
  AND stream_id = $3
`

type ResetStateStreamSubscriberForStreamParams struct {
	Name     string
	TenantID string
	StreamID string
}

// Single-stream rewind: delete the position row for one stream so the
// drain redelivers the current state on its next pass. Used after the
// crypto-shred propagation runbook (ADR 0024 § Crypto-shred).
func (q *Queries) ResetStateStreamSubscriberForStream(ctx context.Context, arg ResetStateStreamSubscriberForStreamParams) error {
	_, err := q.db.Exec(ctx, resetStateStreamSubscriberForStream, arg.Name, arg.TenantID, arg.StreamID)
	return err
}

const upsertStateStreamPosition = `-- name: UpsertStateStreamPosition :exec
INSERT INTO state_stream_subscribers (
    name, tenant_id, stream_id, last_delivered_version, updated_at
) VALUES (
    $1, $2, $3, $4, clock_timestamp()
)
ON CONFLICT (name, tenant_id, stream_id) DO UPDATE SET
    last_delivered_version = GREATEST(state_stream_subscribers.last_delivered_version, EXCLUDED.last_delivered_version),
    updated_at             = clock_timestamp()
`

type UpsertStateStreamPositionParams struct {
	Name     string
	TenantID string
	StreamID string
	Version  int64
}

// Advance the subscriber's position for one stream after a successful
// delivery. Last-delivered-version is monotonically non-decreasing for
// a given (name, tenant_id, stream_id).
func (q *Queries) UpsertStateStreamPosition(ctx context.Context, arg UpsertStateStreamPositionParams) error {
	_, err := q.db.Exec(ctx, upsertStateStreamPosition,
		arg.Name,
		arg.TenantID,
		arg.StreamID,
		arg.Version,
	)
	return err
}
