// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: state_cache.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const deleteStateCacheForType = `-- name: DeleteStateCacheForType :execrows
DELETE FROM state_cache
WHERE tenant_id = $1
  AND type_url  = $2
`

type DeleteStateCacheForTypeParams struct {
	TenantID string
	TypeUrl  string
}

// Wipe state_cache rows for a given type before a rebuild. Returns the
// number of rows deleted.
func (q *Queries) DeleteStateCacheForType(ctx context.Context, arg DeleteStateCacheForTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStateCacheForType, arg.TenantID, arg.TypeUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStateCacheForTypeAllTenants = `-- name: DeleteStateCacheForTypeAllTenants :execrows
DELETE FROM state_cache
WHERE type_url = $1
`

// Cross-tenant variant for full rebuild.
func (q *Queries) DeleteStateCacheForTypeAllTenants(ctx context.Context, typeUrl string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStateCacheForTypeAllTenants, typeUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getState = `-- name: GetState :one
SELECT type_url, state, version, terminal, updated_at
FROM state_cache
WHERE tenant_id = $1
  AND stream_id = $2
`

type GetStateParams struct {
	TenantID string
	StreamID string
}

type GetStateRow struct {
	TypeUrl   string
	State     json.RawMessage
	Version   int64
	Terminal  bool
	UpdatedAt time.Time
}

// Tier 1 point lookup. Returns nothing if the stream has no cached
// state (either never written or the aggregate is not opted in).
func (q *Queries) GetState(ctx context.Context, arg GetStateParams) (GetStateRow, error) {
	row := q.db.QueryRow(ctx, getState, arg.TenantID, arg.StreamID)
	var i GetStateRow
	err := row.Scan(
		&i.TypeUrl,
		&i.State,
		&i.Version,
		&i.Terminal,
		&i.UpdatedAt,
	)
	return i, err
}

const listStates = `-- name: ListStates :many
SELECT tenant_id, stream_id, type_url, state, version, terminal, updated_at
FROM state_cache
WHERE tenant_id      = $1
  AND type_url       = $2
  AND stream_id      > $3
ORDER BY stream_id
LIMIT $4
`

type ListStatesParams struct {
	TenantID      string
	TypeUrl       string
	AfterStreamID string
	MaxRows       int32
}

// Paged listing of cached states for a given type_url. Pass the
// stream_id of the last row in the previous page as @after_stream_id
// to fetch the next page; start with @after_stream_id = ”.
func (q *Queries) ListStates(ctx context.Context, arg ListStatesParams) ([]StateCache, error) {
	rows, err := q.db.Query(ctx, listStates,
		arg.TenantID,
		arg.TypeUrl,
		arg.AfterStreamID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StateCache
	for rows.Next() {
		var i StateCache
		if err := rows.Scan(
			&i.TenantID,
			&i.StreamID,
			&i.TypeUrl,
			&i.State,
			&i.Version,
			&i.Terminal,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatesAll = `-- name: ListStatesAll :many
SELECT tenant_id, stream_id, type_url, state, version, terminal, updated_at
FROM state_cache
WHERE type_url      = $1
  AND (tenant_id, stream_id) > ($2, $3)
ORDER BY tenant_id, stream_id
LIMIT $4
`

type ListStatesAllParams struct {
	TypeUrl       string
	AfterTenantID string
	AfterStreamID string
	MaxRows       int32
}

// Cross-tenant variant. Admin/operator-scope use only.
func (q *Queries) ListStatesAll(ctx context.Context, arg ListStatesAllParams) ([]StateCache, error) {
	rows, err := q.db.Query(ctx, listStatesAll,
		arg.TypeUrl,
		arg.AfterTenantID,
		arg.AfterStreamID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StateCache
	for rows.Next() {
		var i StateCache
		if err := rows.Scan(
			&i.TenantID,
			&i.StreamID,
			&i.TypeUrl,
			&i.State,
			&i.Version,
			&i.Terminal,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStateCache = `-- name: UpsertStateCache :exec

INSERT INTO state_cache (
    tenant_id, stream_id, type_url, state, version, terminal, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    clock_timestamp()
)
ON CONFLICT (tenant_id, stream_id) DO UPDATE SET
    type_url   = EXCLUDED.type_url,
    state      = EXCLUDED.state,
    version    = EXCLUDED.version,
    terminal   = EXCLUDED.terminal,
    updated_at = EXCLUDED.updated_at
`

type UpsertStateCacheParams struct {
	TenantID string
	StreamID string
	TypeUrl  string
	State    json.RawMessage
	Version  int64
	Terminal bool
}

// state_cache queries (ADR 0020 Tier 1).
//
// One row per (tenant_id, stream_id). Written transactionally with
// events via UpsertStateCache (called from Append). Read via GetState /
// ListStates / ListStatesAll.
// Atomic upsert: insert on first append, update on subsequent. Called
// from within the events-append transaction.
func (q *Queries) UpsertStateCache(ctx context.Context, arg UpsertStateCacheParams) error {
	_, err := q.db.Exec(ctx, upsertStateCache,
		arg.TenantID,
		arg.StreamID,
		arg.TypeUrl,
		arg.State,
		arg.Version,
		arg.Terminal,
	)
	return err
}
