// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriber_dlq.sql

package db

import (
	"context"
	"time"
)

const clearSubscriberDLQ = `-- name: ClearSubscriberDLQ :execrows
DELETE FROM subscriber_dlq
WHERE subscriber_name = $1
  AND ($2::text = '' OR tenant_id = $2)
`

type ClearSubscriberDLQParams struct {
	SubscriberName string
	TenantID       string
}

// Operator action: drop every DLQ row for one subscriber (typically
// after a state_stream.Drain refresh has caught the subscriber up).
func (q *Queries) ClearSubscriberDLQ(ctx context.Context, arg ClearSubscriberDLQParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearSubscriberDLQ, arg.SubscriberName, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSubscriberDLQRow = `-- name: DeleteSubscriberDLQRow :exec
DELETE FROM subscriber_dlq
WHERE subscriber_name = $1
  AND tenant_id       = $2
  AND first_event_id  = $3
`

type DeleteSubscriberDLQRowParams struct {
	SubscriberName string
	TenantID       string
	FirstEventID   string
}

// Delete a single DLQ row after operator-driven replay. Keyed by the
// batch's first event id (uniquely identifies the failed batch).
func (q *Queries) DeleteSubscriberDLQRow(ctx context.Context, arg DeleteSubscriberDLQRowParams) error {
	_, err := q.db.Exec(ctx, deleteSubscriberDLQRow, arg.SubscriberName, arg.TenantID, arg.FirstEventID)
	return err
}

const insertSubscriberDLQ = `-- name: InsertSubscriberDLQ :exec

INSERT INTO subscriber_dlq (
    subscriber_name, tenant_id, stream_id,
    first_event_id, event_ids, type_urls,
    last_error, attempts, enqueued_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
ON CONFLICT (subscriber_name, tenant_id, first_event_id) DO UPDATE SET
    event_ids   = EXCLUDED.event_ids,
    type_urls   = EXCLUDED.type_urls,
    stream_id   = EXCLUDED.stream_id,
    last_error  = EXCLUDED.last_error,
    attempts    = EXCLUDED.attempts,
    enqueued_at = EXCLUDED.enqueued_at
`

type InsertSubscriberDLQParams struct {
	SubscriberName string
	TenantID       string
	StreamID       string
	FirstEventID   string
	EventIds       []string
	TypeUrls       []string
	LastError      string
	Attempts       int32
	EnqueuedAt     time.Time
}

// subscriber_dlq queries (ADR 0025, batched per ADR 0029).
// Capture one exhausted subscriber command-batch. INSERT-on-conflict-
// update keeps the most recent attempt info if the same (subscriber,
// tenant, first_event_id) re-DLQs (rare — happens on replay after
// partial recovery).
func (q *Queries) InsertSubscriberDLQ(ctx context.Context, arg InsertSubscriberDLQParams) error {
	_, err := q.db.Exec(ctx, insertSubscriberDLQ,
		arg.SubscriberName,
		arg.TenantID,
		arg.StreamID,
		arg.FirstEventID,
		arg.EventIds,
		arg.TypeUrls,
		arg.LastError,
		arg.Attempts,
		arg.EnqueuedAt,
	)
	return err
}

const listSubscriberDLQ = `-- name: ListSubscriberDLQ :many
SELECT subscriber_name, tenant_id, stream_id, first_event_id,
       event_ids, type_urls, last_error, attempts, enqueued_at
FROM subscriber_dlq
WHERE subscriber_name = $1
  AND ($2::text = '' OR tenant_id = $2)
ORDER BY enqueued_at
LIMIT $3
`

type ListSubscriberDLQParams struct {
	SubscriberName string
	TenantID       string
	MaxRows        int32
}

// Operator dashboard query. Tenant filter: ” = cross-tenant.
func (q *Queries) ListSubscriberDLQ(ctx context.Context, arg ListSubscriberDLQParams) ([]SubscriberDlq, error) {
	rows, err := q.db.Query(ctx, listSubscriberDLQ, arg.SubscriberName, arg.TenantID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriberDlq
	for rows.Next() {
		var i SubscriberDlq
		if err := rows.Scan(
			&i.SubscriberName,
			&i.TenantID,
			&i.StreamID,
			&i.FirstEventID,
			&i.EventIds,
			&i.TypeUrls,
			&i.LastError,
			&i.Attempts,
			&i.EnqueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
