// DBOS-mode emission for protoc-gen-es-go. Activated when buf
// invokes the plugin with opt: runtime=dbos. Emits a DBOSService
// struct per aggregate with one workflow function per command type.
//
// The generated functions have the dbos.Workflow[P, R] signature
// expected by dbos.RegisterWorkflow:
//
//	func(ctx dbossdk.DBOSContext, cmd *Create) (*Invoice, error)
//
// Same shape as the Restate-mode RestateService methods, just with
// a different context type and no service-name override (DBOS
// derives workflow names from FQN; codegen explicitly sets them via
// dbos.WithWorkflowName at registration time — recipe 14).
//
// See ADR 0026 § 3.
package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

// Import paths the generated DBOS-handler code refers to.
var (
	cwdbosPkg = protogen.GoImportPath("github.com/laenenai/eventstore/adapters/cmdworkflow/dbos")
	dbosSDK   = protogen.GoImportPath("github.com/dbos-inc/dbos-transact-golang/dbos")
)

// generateDBOSFile is called by main.go when runtime=dbos is
// configured. Emits handler files; core sum_type / codec / projection
// emission is skipped in this mode.
func generateDBOSFile(plugin *protogen.Plugin, file *protogen.File) error {
	aggregates, err := findAggregatesWithAnnotatedCommands(file)
	if err != nil {
		return err
	}
	if len(aggregates) == 0 {
		return nil
	}

	rootImport := string(file.GoImportPath)
	dbosImport := protogen.GoImportPath(
		"github.com/laenenai/eventstore/adapters/cmdworkflow/dbos/gen" +
			rootImport[len("github.com/laenenai/eventstore/gen"):],
	)
	dbosPkgName := string(file.GoPackageName) + "dbos"

	out := plugin.NewGeneratedFile(
		file.GeneratedFilenamePrefix+"_dbos_es.pb.go",
		dbosImport,
	)
	out.P("// Code generated by protoc-gen-es-dbos. DO NOT EDIT.")
	out.P("// source: ", file.Desc.Path())
	out.P()
	out.P("package ", dbosPkgName)
	out.P()

	for _, agg := range aggregates {
		agg.rootImport = file.GoImportPath
		agg.rootPkgName = string(file.GoPackageName)
		variants, err := collectVariants(agg)
		if err != nil {
			return err
		}
		emitDBOSService(out, agg, variants)
	}
	return nil
}

// emitDBOSService writes the DBOSService struct + one workflow
// function per command variant.
func emitDBOSService(out *protogen.GeneratedFile, agg *aggregate, variants []commandVariantInfo) {
	stateName := out.QualifiedGoIdent(agg.rootImport.Ident(agg.state.GoIdent.GoName))
	cmdIface := out.QualifiedGoIdent(agg.rootImport.Ident(agg.commandSumTypeName))

	esWithTenant := out.QualifiedGoIdent(esPkg.Ident("WithTenant"))
	esNewStreamID := out.QualifiedGoIdent(esPkg.Ident("NewStreamID"))
	cmdwfWorkflow := out.QualifiedGoIdent(cmdwfPkg.Ident("Workflow"))
	withContext := out.QualifiedGoIdent(cwdbosPkg.Ident("WithContext"))
	dbosContext := out.QualifiedGoIdent(dbosSDK.Ident("DBOSContext"))
	bgCtx := out.QualifiedGoIdent(contextPkg.Ident("Background"))

	svcName := "DBOSService"
	out.P("// ", svcName, " exposes the ", stateName, " aggregate as a set of")
	out.P("// DBOS workflows. Register each method with dbos.RegisterWorkflow")
	out.P("// before calling dctx.Launch().")
	out.P("type ", svcName, " struct {")
	out.P("\tWorkflow *", cmdwfWorkflow, "[*", stateName, ", ", cmdIface, "]")
	out.P("}")
	out.P()
	out.P("// New", svcName, " returns a DBOS-registerable service backed by wf.")
	out.P("// Also wires durable Async fan-out: subsequent Async subscriber")
	out.P("// dispatches go through dbos.RunWorkflow targeting AsyncDispatch,")
	out.P("// keyed by <streamType>:<subscriberName>:<eventID> for dedup.")
	out.P("func New", svcName, "(wf *", cmdwfWorkflow, "[*", stateName, ", ", cmdIface, "]) *", svcName, " {")
	out.P("\ts := &", svcName, "{Workflow: wf}")
	out.P("\twf.SetAsyncSend(s.sendAsync)")
	out.P("\treturn s")
	out.P("}")
	out.P()

	// One workflow method per command variant.
	for _, v := range variants {
		cmdName := out.QualifiedGoIdent(agg.rootImport.Ident(v.msg.GoIdent.GoName))
		streamGetter := "Get" + v.streamIDFld.GoName + "()"
		tenantGetter := "Get" + v.tenantIDFld.GoName + "()"
		out.P("func (s *", svcName, ") ", v.msg.GoIdent.GoName, "(ctx ", dbosContext, ", cmd *", cmdName, ") (*", stateName, ", error) {")
		out.P("\ttenant := cmd.", tenantGetter)
		out.P("\tsid, err := ", esNewStreamID, "(tenant, \"", agg.name, "\", cmd.", streamGetter, ")")
		out.P("\tif err != nil { return nil, err }")
		out.P("\tstdCtx := ", withContext, "(", esWithTenant, "(", bgCtx, "(), tenant), ctx)")
		out.P("\treturn s.Workflow.HandleCmd(stdCtx, sid, cmd)")
		out.P("}")
		out.P()
	}

	// AsyncDispatch + sendAsync — durable Async fan-out path.
	cmdwfAsyncPayload := out.QualifiedGoIdent(cmdwfPkg.Ident("AsyncPayload"))
	cwDBOSFromCtx := out.QualifiedGoIdent(cwdbosPkg.Ident("FromContext"))
	cwDBOSErrNoCtx := out.QualifiedGoIdent(cwdbosPkg.Ident("ErrNoDBOSContext"))
	dbosRunWorkflow := out.QualifiedGoIdent(dbosSDK.Ident("RunWorkflow"))
	dbosWithWfID := out.QualifiedGoIdent(dbosSDK.Ident("WithWorkflowID"))
	ctxType := out.QualifiedGoIdent(contextPkg.Ident("Context"))

	out.P("// AsyncDispatch is the DBOS workflow that runs an Async subscriber's")
	out.P("// delivery + retry + exhausted policy. Register it alongside the")
	out.P("// per-command workflows; the framework's spawnAsync dispatches to")
	out.P("// it on every Async subscriber × event.")
	out.P("func (s *", svcName, ") AsyncDispatch(ctx ", dbosContext, ", payload ", cmdwfAsyncPayload, ") (struct{}, error) {")
	out.P("\tstdCtx := ", withContext, "(", bgCtx, "(), ctx)")
	out.P("\treturn struct{}{}, s.Workflow.DispatchAsync(stdCtx, payload.SubscriberName, payload.EnvBytes)")
	out.P("}")
	out.P()
	out.P("// sendAsync is the AsyncSend wired into the Workflow at construction.")
	out.P("// Issues a fire-and-forget dbos.RunWorkflow to AsyncDispatch with the")
	out.P("// workflow id as DBOS's WithWorkflowID — dedup against replays.")
	out.P("func (s *", svcName, ") sendAsync(ctx ", ctxType, ", subscriberName string, envBytes []byte, workflowID string) error {")
	out.P("\tdctx, ok := ", cwDBOSFromCtx, "(ctx)")
	out.P("\tif !ok { return ", cwDBOSErrNoCtx, " }")
	out.P("\t_, err := ", dbosRunWorkflow, "(dctx, s.AsyncDispatch, ", cmdwfAsyncPayload, "{")
	out.P("\t\tSubscriberName: subscriberName,")
	out.P("\t\tEnvBytes:       envBytes,")
	out.P("\t}, ", dbosWithWfID, "(workflowID))")
	out.P("\treturn err")
	out.P("}")
	out.P()
}
