// protoc-gen-es-go is the framework's codegen plugin (ADR 0016).
// Invoked by `buf generate` to produce framework-specific Go code from
// .proto files: sealed-interface sum types + Codec implementations,
// typed StreamID wrappers per aggregate, decider stubs, type-URL
// registry, and (in later iterations) PII manifests and upcaster
// scaffolds.
//
// This commit ships the plugin scaffold and verifies the buf-plugin
// invocation pipeline end-to-end. Actual sum-type and Codec generation
// arrive in the next commit.
package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			if err := generateFile(plugin, file); err != nil {
				return err
			}
		}
		return nil
	})
}

// generateFile emits one *_es.pb.go output file per input .proto file.
// At this iteration the file is a header placeholder; subsequent
// commits fill in the sum-type, codec, and StreamID generation logic.
func generateFile(plugin *protogen.Plugin, file *protogen.File) error {
	out := plugin.NewGeneratedFile(
		file.GeneratedFilenamePrefix+"_es.pb.go",
		file.GoImportPath,
	)
	out.P("// Code generated by protoc-gen-es-go. DO NOT EDIT.")
	out.P("// source: ", file.Desc.Path())
	out.P()
	out.P("package ", file.GoPackageName)
	out.P()
	out.P("// This file is generated by the eventstore framework's codegen plugin.")
	out.P("// Sum-type interfaces, Codecs, typed StreamIDs, and decider stubs")
	out.P("// will be emitted here in subsequent commits.")
	return nil
}
