// protoc-gen-es-go is the framework's codegen plugin (ADR 0016).
//
// Invoked by `buf generate`, it produces framework-specific Go code
// from .proto files. This iteration emits sealed-interface sum types
// and Codec implementations driven by the es.v1.sum_type option.
// Typed StreamIDs and decider stubs arrive in subsequent commits.
package main

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"

	esv1 "github.com/laenenai/eventstore/gen/es/v1"
)

// Import paths the generated code refers to.
var (
	aggregatePkg = protogen.GoImportPath("github.com/laenenai/eventstore/aggregate")
	protoPkg     = protogen.GoImportPath("google.golang.org/protobuf/proto")
	fmtPkg       = protogen.GoImportPath("fmt")
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		// Note: buf invokes this plugin once per .proto file (default
		// strategy=directory). Each invocation's plugin.Files contains
		// the target file plus its transitive imports. Cross-file
		// artifacts (e.g., a process-wide type-URL registry) are
		// assembled at runtime via init() registrations, not emitted as
		// a single big file at codegen time.
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			if err := generateFile(plugin, file); err != nil {
				return err
			}
		}
		return nil
	})
}

// sumType captures one message annotated `option (es.v1.sum_type) = "X"`,
// holding a oneof whose variants become the sealed-interface variants.
type sumType struct {
	interfaceName string             // e.g., "Command"
	container     *protogen.Message  // wrapper message (e.g., Commands)
	oneof         *protogen.Oneof    // the oneof inside
	variants      []*protogen.Message
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) error {
	sumTypes, err := findSumTypes(file)
	if err != nil {
		return err
	}
	if len(sumTypes) == 0 {
		return nil
	}

	out := plugin.NewGeneratedFile(
		file.GeneratedFilenamePrefix+"_es.pb.go",
		file.GoImportPath,
	)
	out.P("// Code generated by protoc-gen-es-go. DO NOT EDIT.")
	out.P("// source: ", file.Desc.Path())
	out.P()
	out.P("package ", file.GoPackageName)
	out.P()

	for _, st := range sumTypes {
		emitSumType(out, st)
	}
	return nil
}

// findSumTypes walks the file's messages and returns those annotated
// with `option (es.v1.sum_type) = "Name"`. Returns an error for
// malformed annotations (multiple oneofs, non-message variants).
func findSumTypes(file *protogen.File) ([]*sumType, error) {
	var out []*sumType
	for _, msg := range file.Messages {
		name, ok := extractSumTypeName(msg)
		if !ok {
			continue
		}
		if len(msg.Oneofs) != 1 {
			return nil, fmt.Errorf(
				"%s: es.v1.sum_type requires exactly one oneof, found %d",
				msg.GoIdent.GoName, len(msg.Oneofs),
			)
		}
		st := &sumType{
			interfaceName: name,
			container:     msg,
			oneof:         msg.Oneofs[0],
		}
		for _, field := range msg.Oneofs[0].Fields {
			if field.Message == nil {
				return nil, fmt.Errorf(
					"%s.%s: sum_type oneof variants must be message types",
					msg.GoIdent.GoName, field.GoName,
				)
			}
			st.variants = append(st.variants, field.Message)
		}
		out = append(out, st)
	}
	return out, nil
}

// extractSumTypeName returns the value of (es.v1.sum_type) if set, "" otherwise.
func extractSumTypeName(msg *protogen.Message) (string, bool) {
	opts, ok := msg.Desc.Options().(*descriptorpb.MessageOptions)
	if !ok || opts == nil {
		return "", false
	}
	if !proto.HasExtension(opts, esv1.E_SumType) {
		return "", false
	}
	name, _ := proto.GetExtension(opts, esv1.E_SumType).(string)
	return name, name != ""
}

// getSchemaVersion returns the value of (es.v1.schema_version) on a
// variant message; defaults to 1.
func getSchemaVersion(msg *protogen.Message) uint32 {
	opts, ok := msg.Desc.Options().(*descriptorpb.MessageOptions)
	if !ok || opts == nil {
		return 1
	}
	if !proto.HasExtension(opts, esv1.E_SchemaVersion) {
		return 1
	}
	v, _ := proto.GetExtension(opts, esv1.E_SchemaVersion).(uint32)
	if v == 0 {
		return 1
	}
	return v
}

// emitSumType writes the sealed interface, marker methods, and Codec
// for one sum type.
func emitSumType(out *protogen.GeneratedFile, st *sumType) {
	iface := st.interfaceName
	marker := "is" + iface

	// ----- Sealed interface ---------------------------------------------
	out.P("// ", iface, " is the sealed interface for the ", st.container.GoIdent.GoName, " sum type.")
	out.P("// Variants implement this via the unexported ", marker, "() marker method.")
	out.P("type ", iface, " interface {")
	out.P("\t", marker, "()")
	out.P("}")
	out.P()

	// ----- Variant marker methods ---------------------------------------
	for _, v := range st.variants {
		out.P("func (*", v.GoIdent.GoName, ") ", marker, "() {}")
	}
	out.P()

	// ----- Action() string ----------------------------------------------
	// Stable per-variant identifier — the variant's full proto type
	// name (e.g., "myapp.party.v1.Approve"). Useful for authz wrappers,
	// metrics labels, trace span names, audit log enrichment, and
	// anywhere else a stable per-command-type identifier is needed.
	// Emitted for events too; semantically it's the event's type name.
	out.P("// Stable per-variant identifiers — full proto type names.")
	out.P("// Useful for authz, metrics, tracing, and audit annotation.")
	for _, v := range st.variants {
		out.P("func (*", v.GoIdent.GoName, ") Action() string { return \"", v.Desc.FullName(), "\" }")
	}
	out.P()

	// ----- Codec --------------------------------------------------------
	codec := iface + "Codec"
	encodedEvent := out.QualifiedGoIdent(aggregatePkg.Ident("EncodedEvent"))
	codecIface := out.QualifiedGoIdent(aggregatePkg.Ident("Codec"))
	protoMarshal := out.QualifiedGoIdent(protoPkg.Ident("Marshal"))
	protoUnmarshal := out.QualifiedGoIdent(protoPkg.Ident("Unmarshal"))
	fmtErrorf := out.QualifiedGoIdent(fmtPkg.Ident("Errorf"))

	out.P("// ", codec, " encodes and decodes ", iface, " variants on the wire.")
	out.P("// Implements aggregate.Codec[", iface, "].")
	out.P("type ", codec, " struct{}")
	out.P()
	out.P("// Compile-time assertion that the codec satisfies the framework contract.")
	out.P("var _ ", codecIface, "[", iface, "] = ", codec, "{}")
	out.P()

	// Encode
	out.P("// Encode marshals v as proto bytes and produces an EncodedEvent")
	out.P("// tagged with the variant's full proto type name.")
	out.P("func (", codec, ") Encode(v ", iface, ") (", encodedEvent, ", error) {")
	out.P("\tswitch x := v.(type) {")
	for _, v := range st.variants {
		out.P("\tcase *", v.GoIdent.GoName, ":")
		out.P("\t\tb, err := ", protoMarshal, "(x)")
		out.P("\t\tif err != nil {")
		out.P("\t\t\treturn ", encodedEvent, "{}, err")
		out.P("\t\t}")
		out.P("\t\treturn ", encodedEvent, "{")
		out.P("\t\t\tPayload:       b,")
		out.P("\t\t\tTypeURL:       \"", v.Desc.FullName(), "\",")
		out.P("\t\t\tSchemaVersion: ", getSchemaVersion(v), ",")
		out.P("\t\t}, nil")
	}
	out.P("\t}")
	out.P("\treturn ", encodedEvent, "{}, ", fmtErrorf, "(\"", iface, "Codec.Encode: unknown variant type %T\", v)")
	out.P("}")
	out.P()

	// Decode
	out.P("// Decode unmarshals the proto payload back into the variant identified")
	out.P("// by typeURL. The schemaVersion is passed through for upcaster")
	out.P("// dispatch (ADR 0013); this generated codec does not perform upcasting.")
	out.P("func (", codec, ") Decode(typeURL string, _ uint32, payload []byte) (", iface, ", error) {")
	out.P("\tswitch typeURL {")
	for _, v := range st.variants {
		out.P("\tcase \"", v.Desc.FullName(), "\":")
		out.P("\t\tx := &", v.GoIdent.GoName, "{}")
		out.P("\t\tif err := ", protoUnmarshal, "(payload, x); err != nil {")
		out.P("\t\t\treturn nil, err")
		out.P("\t\t}")
		out.P("\t\treturn x, nil")
	}
	out.P("\t}")
	out.P("\treturn nil, ", fmtErrorf, "(\"", iface, "Codec.Decode: unknown type_url %q\", typeURL)")
	out.P("}")
	out.P()
}
